international-labour-organization/designsystem

- package.json
Should fix builds broken by the fact that Netlify now provides native support for pnpm. 
Note that this also requires changing the buildscript in Netlify to (for example)
```
pnpm build:react
```
and setting `NETLIFY_USE_PNPM=true`
Reference:
- [New for Netlify Build: Out of the box support for pnpm](https://www.netlify.com/blog/how-to-use-pnpm-with-netlify-build/)
- [Twitter convo with Lukas Holzer/@luka5c0m](https://twitter.com/luka5c0m/status/1583117359988236288)
> Fix: Netlify support for pnpm

- .changeset/forty-months-lie.md
- .gitignore
- packages/styles/README.md
- packages/styles/gulpfile.mjs
- packages/styles/package.json
- pnpm-lock.yaml
This creates a new build folder called `css` which includes both the bundled stylesheets as well as the compiled css for each of the components.
That way it should be possible to import the `css` like this:
```scss
import "@ilo-org/styles/css/components/accordion";
```
It also updates the docs to make this clear. Once this gets merged, create a follow up issue to remove the legacy `build` directory, a breaking change that can wait for the v1.
Fixes #335
> Feat/Styles: Export compiled CSS for individual components

- .changeset/big-eyes-join.md
- packages/twig/src/patterns/components/card/card.twig
- packages/twig/src/patterns/components/card/card.wingsuit.yml
Add support for reponsive images in the Card component. The `image` field can take either a string (for a non-responsive image) or an array of objects with an `src` and `breakpoint` property. The `image` field of the card now works the same way as the `url` field of the Image component. This also adds an `imageAlt` field that applies a describe alt tag to the image.
> Feat/Twig: Support responsive images in cards

- .changeset/popular-peas-reply.md
- packages/twig/src/patterns/components/callout/callout.twig
- packages/twig/src/patterns/components/callout/callout.wingsuit.yml
This replaces the <button> html element in the Callout component with the Button Twig component, allowing it to act as either a button or a link.
This PR will trigger a minor release that however includes a breaking change. This is a violation of semver which is tolerated while the package is still in >v1.0.0. Future changes of this sort should not be allowed once the library has reached v1.0.0.
The `buttonLabel` field in the `Callout` component is replaced with a `button` field that takes a subject of the fields passed to the underlying Button. The `buttonLabel` field is no long used.
The Button in the Callout applies the styles of a `small` and `secondary` Button, which can't be overridden.
The available fields that can be set through the `button` property are:
```json
{
"label": "The …
```
> Fix/Twig: Allow button in Callout to act as a link

- .changeset/ten-jobs-chew.md
- packages/styles/scss/components/_tabs.scss
Added background color white to the content tabs, to make sure it will be white when used different background colors on the component.
Before:
After:
> fix(styles): Added background color to the content tabs

- .changeset/green-jokes-allow.md
- packages/styles/scss/components/_cardgroup.scss
Added the same space between the cards, 32px.
Before:
After:
> fix(styles): Changed space between cards

- .changeset/gold-pumas-refuse.md
- packages/styles/scss/components/_cardgroup.scss
- packages/twig/src/patterns/components/cardgroup/cardgroup.twig
- packages/twig/src/patterns/components/cardgroup/cardgroup.wingsuit.yml
- In Card Group, set `theme` and `type` properties for Cards on Card Group, not on invididual cards
- Use `cardcount` to determine how many cards should be in a row and how wide they should be.
> Fix/Twig: cardgroup add theme and type settings

- .changeset/rude-socks-eat.md
- .changeset/wet-peas-taste.md
- packages/styles/scss/components/_featurecard.scss
- packages/twig/src/patterns/components/cardgroup/cardgroup.twig
- packages/twig/src/patterns/components/cardgroup/cardgroup.wingsuit.yml
You need the `size` attribute in Card Group to manage the layout options of the cards, even if the width of the cards is determined by the number of cards in a row.
> Twig: Replace size attribute in Card Group

- .changeset/neat-hotels-try.md
- .changeset/rare-apples-add.md
- .changeset/shiny-chicken-call.md
- .changeset/strong-bananas-jam.md
- packages/styles/scss/components/_card.scss
- packages/styles/scss/components/_cardgroup.scss
- packages/styles/scss/components/_featurecard.scss
- packages/twig/src/patterns/components/cardgroup/cardgroup.wingsuit.yml
- Avoid card wrappers getting stretched beyond the width of the actual component
- Cards should have white background by default
- All cards in card group should be the same height.
- In Feature Card, push dates and ctas to the bottom of the card
> Styles: card layout fixes

- .changeset/strong-zoos-tap.md
- packages/twig/src/patterns/components/modal/modal.twig
Add a block wrap the modal content so it can be overriden.
> feat(twig): Add a block to wrap the modal content

- .changeset/afraid-pants-wink.md
- packages/twig/src/patterns/components/form/formcontrol.twig
With this change it will be possible to merge default classes from Drupal if they are needed for the functionality of the forms.
> feat(twig): formControlClass variable set with default value

- .changeset/blue-knives-fix.md
- packages/styles/scss/components/_checkbox.scss
- packages/styles/scss/components/_dropdown.scss
- packages/styles/scss/components/_fieldset.scss
- packages/styles/scss/components/_file-upload.scss
- packages/styles/scss/components/_form.scss
- packages/styles/scss/components/_input.scss
- packages/styles/scss/components/_radio.scss
- packages/styles/scss/components/_searchfield.scss
- packages/styles/scss/components/_textarea.scss
- packages/styles/scss/components/_textinput.scss
- packages/themes/tokens/opacity/base.json
Fixes incorrect opacity values in production where cssnano was clamping percentages to 1%.
> Hotfix(styles/themes): set all opacity values with decimals

- .changeset/many-pots-begin.md
- .changeset/neat-hotels-prove.md
- .changeset/silent-countries-yell.md
- .changeset/tender-carpets-tie.md
- packages/styles/scss/components/_breadcrumb.scss
- packages/styles/scss/components/_hero.scss
- packages/styles/scss/components/_herocard.scss
- packages/twig/src/patterns/components/hero/hero.twig
Align Hero Card content with main body content when `justify` is set to `start` or `offset`. 
Fixes #580
> Twig/Styles: Align Hero Content to main content area

- .changeset/witty-trees-greet.md
- packages/styles/scss/_reset.scss
Fixes #546 
Upon investigation, the issue affected more than just the search field outlined in the issue and also affected all inputs and text areas. As such, this fix addresses all of it.
It is highly suspect that the CSS reset being used in this project does not already cover this. It seems like it is out of date. @justintemps  perhaps we should consider moving to a more maintained css reset.
> fix(styles): fixed input border radius on iOS Safari

- .changeset/red-ghosts-smile.md
- packages/styles/scss/components/_accordion.scss
Reduced accordion inner panel bottom padding.
---
The accordion component inside Figma has no open-state example 
Fixes #572
> fix(styles): reduced padding for accordion inner panel

- .changeset/mighty-ducks-return.md
- packages/twig/src/patterns/components/linklist/index.js
- packages/twig/src/patterns/components/linklist/linklist.behavior.js
- packages/twig/src/patterns/components/linklist/linklist.js
- packages/twig/src/patterns/components/linklist/linklist.twig
I added a twig implementation for external links inside `linklist` component to open in a new browser tab. Implementation attaches `target=_blank" based on **origin** comparison using [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).
https://github.com/international-labour-organization/designsystem/assets/36326203/80e17054-d909-4384-aee4-2ca80441e157
Fixes #547
> fix(twig): implemented tab strategy for external links

- .changeset/quiet-pandas-scream.md
- packages/styles/scss/components/_tabs.scss
**Change :-** 
* Add top border to hover state of the tabs
Fixes: https://github.com/international-labour-organization/designsystem/issues/548
> Fix(Style): Tab button hover state

- .changeset/curvy-olives-obey.md
- packages/styles/scss/components/_linklist.scss
At first glance current implementation hovers the indicator(arrow) for the indented list item `(Asset 1)`, but if we force the `:hover` state for the actual anchor tag arrow has no effect `(Asset 2)`. This might be a big issue during keyboard navigation `(Asset 3`)`
> Asset 1
> Asset 2
> Asset 3
https://github.com/international-labour-organization/designsystem/assets/36326203/7539e81b-8107-499b-ba61-aab342368c36
Current implementation fixes the issue by adding hover directly to anchor(`<a>`) item inside indented `LinkList`
https://github.com/international-labour-organization/designsystem/assets/36326203/66829c8d-f37a-4361-ab3a-305d8cc2dc27
Closing #444
> fix(styles): added hover effect for anchor item

- .changeset/beige-bugs-buy.md
- packages/styles/scss/components/_breadcrumb.scss
**Change :-** 
* Truncate text of breadcrumbs when it exceeds 40 chars
Fixes: https://github.com/international-labour-organization/designsystem/issues/564
> Fix(Style): Truncate breadcrumb for long text

- .changeset/blue-lizards-pay.md
- packages/styles/scss/components/_tag.scss
- packages/themes/tokens/widths/tags.json
Issue :- https://github.com/international-labour-organization/designsystem/issues/400
Problem
* Currently long texts in tags take up a lot of space.
Solution
* Text should truncate by showing an ellipsis so that it does not exceed 190px as per the design.
Development
* Modified css by adding a max-width of 190px and a text-overflow style.
* Added variable $widths-tags-max-width
Screenshot
> Fix(Style): Truncate long text in tags

- .changeset/shiny-glasses-admire.md
- packages/styles/scss/_reset.scss
- packages/styles/scss/components/_richtext.scss
Issue :- https://github.com/international-labour-organization/designsystem/issues/336
Problem
**Based on the investigation there are two issues why this is happening.**
* Currently both ul and ol have their list marker removed.
* Both the ul and ol have a common style set to overide the marker.
Solution
* Remove the list marker for ol as numbers need to be displayed. 
* Seperate out the marker styles for the ul and ol as they are different. 
Development
* Modified css by separting out the ul and ol styles applied for the marker 
* Added seperate padding for ul and ol as it differs based on the marker. 
* Styles needed to be modified for the rtl section as well
Screenshot :-
> Fix(Style): ol showing as ul

- .changeset/silent-singers-cross.md
- packages/styles/scss/components/_datacard.scss
- packages/styles/scss/components/_detailcard.scss
- packages/styles/scss/components/_promocard.scss
- packages/styles/scss/components/_statcard.scss
- packages/styles/scss/components/_textcard.scss
Current `PR` is primarily focused on `twig` part, `react` components are styled differently and have no breakpoint width issue, but since `scss` is shared I included `react` in the changeset too.
This table displays which cards had the problem with which sizes
| Card Type      | Component name   | Size                   | Width Problem |
| -------------- | ---------------- | ---------------------- | ------------- |
| Default        | `card`           | *                      | ❌            |
| Text Card      | `card_text`      | standard, narrow       | ✅            |
| Details Card   | `card_detail`    | standard, narrow       | ✅            |
| Promo Card     | `card_promo`     | narrow                 | ✅            |
| Multilink Card | `card_multilink` | *                      | ❌ …
> fix(style): added full width on mobile viewport for affected cards

- .changeset/metal-peas-exercise.md
- packages/react/src/components/Video/VideoPlayer.tsx
- packages/styles/scss/components/_video.scss
- packages/twig/src/patterns/components/video/video.js
Let's break down this PR into 2 pieces, for `react` and `twig`. This separation is necessary because video components have drastically different implementations.
Twig component uses `video.js` for display, which has its own makeup for controls.
When we hover the button, duration is also styled because we are using the `sibling`(`~`) selector 
```scss
&:hover,
&:focus {
background-color: $color-ux-video-controls-hover-background;
@include iconbutton(
"play",
$spacing-ux-video-bigplaybutton-height,
$spacing-ux-video-bigplaybutton-width,
$color-ux-video-controls-hover-icon
);
& ~ .vjs-duration,
& ~ .ilo--video--controls--duration {
background-color: $color-ux-video-controls-hover-background;
color: $color-ux-video-controls-hover-icon;
}
```
but when we want to invert the behavior we can't …
> fix(style): video timecode hover

- packages/react/.storybook/main.ts
- packages/react/.storybook/preview.tsx
- packages/react/package.json
- packages/twig/apps/storybook/main.js
- packages/twig/package.json
- pnpm-lock.yaml
Added storybook-addon-rtl-direction to both the twig and react storybooks. Now we can switch between ltr and rtl within storybook itself. The addon changes the dir attribute on the html element in the iframe that displays the content of the storybook.
https://github.com/international-labour-organization/designsystem/assets/11556301/41190489-40d6-4708-828d-a4897a1ac42b
Fixes #655
> docs(twig/react): implemented addon to switch text direction

- .changeset/spicy-ads-roll.md
- packages/styles/scss/components/_textinput.scss
- packages/themes/tokens/color/formelements.json
- packages/twig/src/patterns/components/textinput/textinput.wingsuit.yml
Fixes #591 
The Text area already has the desired behaviour (red on error / required, blue when not and in focus). Changed the Text input to have the same behaviour, removed the tokens for the unused invalid state and removed the default pattern in wingsuit so that the Text input behaves as expected when opened by default in storybook.
> fix(styles/themes): fixed text input invalid state

- .changeset/dull-boxes-collect.md
- packages/styles/scss/components/_footer.scss
- packages/styles/scss/components/_linklist.scss
Related component :- 
* The footer uses a linklist component so it will be included in this as well. 
Investigation
* In linklist the right to left class needs to be changed to dir attribute
* There was a design bug found when the rtl toggle has been done which existed in the component previously
Development
* Modified css to use dir attribute selector instead of right-to-left class
* Fixed arrow positioning and side using css styling
Screenshot
**LinkList**
* LTR
* RTL
**Footer**
* LTR
* RTL
> Fix(Style): Refactor and fix RTL style in linklist

- .changeset/silly-taxis-travel.md
- packages/styles/scss/components/_searchfield.scss
Development
* Modified css to use dir attribute selector instead of right-to-left class
Screenshot
* LTR
* RTL
> Refactor RTL style using dir in searchfield

- .changeset/gold-turkeys-change.md
- packages/styles/scss/components/_formcontrol.scss
- packages/styles/scss/components/_textarea.scss
Development
* Modified css to use dir attribute selector instead of right-to-left class.
* Fixed styling issue in rtl.
Screenshot
* LTR
* RTL
> Refactor RTL style using dir in text area

- .changeset/flat-ghosts-invent.md
- packages/styles/scss/components/_card.scss
- packages/styles/scss/components/_cardgroup.scss
- packages/styles/scss/components/_detailcard.scss
- packages/styles/scss/components/_featurecard.scss
- packages/styles/scss/components/_multilinkcard.scss
- packages/styles/scss/components/_promocard.scss
- packages/styles/scss/components/_textcard.scss
Related components used
* Cards
* Card group
* Detail card
* Feature card
* Multi link card
* Promo card
* Text card
Development
* Modified css to use dir attribute selector instead of right-to-left class.
* Removed unnecessary styling 
* Modified arrow side based on rtl in feature card.
* Modified cornercut on promo card and text card to support RTL
Screenshot (Excluded the minor change ones)
**Feature card**
* LTR
* RTL
**Promo card**
*LTR
*RTL
> Refactor RTL style using dir in cards

- .changeset/tough-jobs-repeat.md
- packages/styles/scss/components/_tabs.scss
Development
* Modified css to use dir attribute selector instead of right-to-left class.
Screenshot
* LTR
* RTL
> Refactor RTL style using dir in tabs

- .changeset/brown-garlics-ring.md
- packages/styles/scss/components/_breadcrumb.scss
Issue :- https://github.com/international-labour-organization/designsystem/issues/524
Refactored RTL styles in breadcrumb using `dir="rtl"` global attribute.
> fix(styles): rtl in breadcrumb

- .changeset/happy-cheetahs-marry.md
- packages/styles/scss/components/_dropdown.scss
Development
* Modified css to use dir attribute selector and change the side of the dropdown based on direction
* LTR
* RTL
> Fix(Style): Support rtl in dropdown

- .changeset/gold-cows-grab.md
- packages/styles/scss/components/_navigation.scss
Development
* Modified css to use dir attribute selector.
* Bugfix cornecut in language selector.
* Bugfix language selector icon not changing side in RTL. (Small and large screens) 
* Bugfix more button in menu not shifting based on rtl.
* Bugfix more button not reflecting rtl in small screen.
* Bugfix css styles which existed in previous rtl 
* LTR
* RTL
* LTR
* RTL
> Fix(Style): Support rtl in navigation

- .changeset/popular-carpets-protect.md
- packages/styles/scss/components/_tag.scss
Development
* Removed unnecessary right to left style that sets dir
LTR
RTL
> Fix(Style): Clean up unwanted RTL style in tag

- .changeset/nine-kangaroos-matter.md
- packages/styles/scss/components/_richtext.scss
Development
* Used dir selector instead of right to left class 
LTR
RTL
> Fix(Style): Refactor rtl to use dir in richtext

- .changeset/slimy-seas-drive.md
- packages/styles/scss/components/_socialmedia.scss
Development
* Used dir selector instead of right to left class 
* Remove unwanted css 
LTR
RTL
> Refactor rtl to use dir in social media

- .changeset/tame-nails-float.md
- packages/twig/src/patterns/components/card_multilink/card_multilink.twig
Fixes :- https://github.com/international-labour-organization/designsystem/issues/678
Development
* Check and conditionally render the link if a link arg is passed only.
* Removed the action(hover) states when a link is not available as it could confuse the user.
Notes 
* When a link is not available it comes as an empty string so the length should be checked to ensure if a link is available or not.
> fix(twig): Remove link from multicard when its not available

- .changeset/odd-melons-nail.md
- packages/styles/scss/_functions.scss
- packages/styles/scss/components/_datacard.scss
- packages/styles/scss/components/_detailcard.scss
- packages/styles/scss/components/_factlistcard.scss
- packages/styles/scss/components/_featurecard.scss
- packages/styles/scss/components/_multilinkcard.scss
- packages/styles/scss/components/_promocard.scss
- packages/styles/scss/components/_statcard.scss
- packages/styles/scss/components/_textcard.scss
This PR is a follow-up of #654 and aims to refactor padding values with new spacing tokens for all card components. As mentioned in #637 I don't have access to the foundation file but pretty much all refactoring points I have marked were multiples of 4 so I decided to go with it. 
Here is a refactoring table 
| Card Type      | Component name   | Reworked | Multiple of 4 problem | Design off |
| -------------- | ---------------- | -------- | --------------------- | --------- |
| Text Card      | `_textcard`      | ✅       | ❌                    | ✅        |
| Details Card   | `_detailscard`   | ✅       | ❌                    | ✅        |
| Promo Card     | `_promocard`     | ✅       | ❌                    | ✅        |
| Multilink Card | `_multilinkcard` | ✅       | ❌                    | …
> refactor(styles): reworked bare padding values with new spacing tokens

- .changeset/smart-flies-thank.md
- packages/styles/scss/components/_video.scss
Development
* Convert right to left class to use dir selector attribute
* Fix styles to align play button and duration to the right when rtl is set. (Small/Large screen)
LTR (Small screen)
RTL (Small screen)
LTR (Large screen)
RTL (Large screen)
> Fix(Style): Refactor rtl to use dir in video

- .changeset/nice-icons-scream.md
- packages/styles/scss/components/_button.scss
- packages/styles/scss/components/_loading.scss
- packages/styles/scss/components/_readmore.scss
- packages/styles/scss/components/_tabs.scss
- packages/styles/scss/components/_tag.scss
User Interface Category and Transition categories got new spacing token implementations.
Component List 
-  Loading
-  Button
-  Read more
-  Tabs
- Tags
Spacing values for all mentioned components were checked with the design system and refactored using the new `spacing` helper. Those components have no dependency on other spacing files (`boxpadding.json`, `icon.json`);
By definition of **Spacing** we should only consider `margin` and `padding` properties. So current implementation uses a `spacing` helper only with those properties. But spacing values were used for properties like `width` `height`, `top`, `bottom` etc. For places like this I used literal `pixel-to-rem` to remove the dependency, example
```diff
.ilo--icon {
-  right: calc($spacing-icons-icon-padding-lg - 9px);
-  top: …
```
> New spacing for transitions & user interface category 

- .changeset/sweet-ducks-cheat.md
- packages/styles/scss/components/_callout.scss
- packages/styles/scss/components/_notification.scss
- packages/styles/scss/components/_tooltip.scss
Feedback categories got new spacing token implementations.
- Callout
- Notification
- Tooltip
In [#639](https://github.com/international-labour-organization/designsystem/issues/639), the modal component is also mentioned but it has no legacy spacing.
Here are some demos of improved component spacing
>  Old Callout
> New Callout
- New spacing applied
- The collapsed version is symmetrical
> Old Notification
> New Notification
> New spacing for feedback components

- .changeset/kind-dingos-juggle.md
- packages/styles/scss/components/_image.scss
- packages/styles/scss/components/_video.scss
- Image
- Video
The video component has an overhead implementation its `786 lines` and it's pretty complex to maintain, @justintemps maybe we should open a follow-up to re-organize, re-implement, or separate video styles
> New spacing for media components

- .changeset/tame-birds-hear.md
- packages/styles/scss/components/_hero.scss
When the Hero was set to `justify: start`, long content in the Hero Card would push it size passed the width set by the size class. This was happening because the css variable `--added-offset`, which is used for figuring out the padding between the Hero Card content and the edge of the screen, was set to `0` instead of `0px`. Simply adding `px` fixed it.
> Fix/Styles: Hero Card content expanding its width past the limit set by size class

- .changeset/new-weeks-roll.md
- packages/styles/scss/components/_accordion.scss
- packages/styles/scss/components/_list.scss
- packages/styles/scss/components/_profile.scss
- packages/styles/scss/components/_richtext.scss
- packages/styles/scss/components/_table.scss
Fixes :- https://github.com/international-labour-organization/designsystem/issues/638
Content category is refactored with new spacing token implementations.
* Refactored all of the components above to use new spacing.
**The following components styles had to be modified (Non breaking) to be intact with the multiple of 4px styling.**
* Accordion
* Profile _(Figma designs too have values that are not matching the criteria)_
* Rich text
* Table 
* Accordian styles were not in sync with the design. Padding was refactored to match the design.
* Long text
* Short text
* List styles were not in sync with the design. Padding and margins had to be adjusted accordingly.
* Table styles were not in sync with the design. Padding and margins had to be adjusted accordingly.
> Refactor(styles): Clean up and modify content spacing

- .changeset/sweet-colts-yawn.md
- packages/styles/scss/components/_breadcrumb.scss
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.twig
> Twig/Styles: Breadcrumb shows first link when condensed

- .changeset/famous-drinks-enjoy.md
- packages/styles/scss/components/_accordion.scss
Fixes :- https://github.com/international-labour-organization/designsystem/issues/723
* The icon is in a fixed position and it needs to do mirror when we change to RTL.
**Before** 
**After**
> fix(style)- Support RTL for accordion

- .changeset/chatty-ladybugs-drum.md
- .changeset/wet-feet-applaud.md
- packages/styles/scss/components/_breadcrumb.scss
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.twig
Fixes #728 
This adds a series of conditional checks on the links to prevent the last and first link from being the same link when there are two or less.
> Fix/Twig: Breadcrumb incorrectly assuming >2 links

- .changeset/slow-houses-draw.md
- packages/twig/package.json
- pnpm-lock.yaml
Fixes :- https://github.com/international-labour-organization/designsystem/issues/739
* Add popper as a dependency instead of a dev dependency
> fix(twig) - Add popper as a dependency

- .changeset/great-pugs-appear.md
- packages/twig/src/patterns/components/tooltip/tooltip.twig
Problem :- 
* Currently there is a design bug in the twig when the icon is set to false
Note :- 
* The value false is set a string so it needs to check if the value is "false" 
Screenshot :-
> fix(twig) - Tooltip label issue

- .changeset/fuzzy-seals-agree.md
- packages/react/package.json
- packages/react/src/components/Tooltip/Tooltip.args.ts
- packages/react/src/components/Tooltip/Tooltip.props.ts
- packages/react/src/components/Tooltip/Tooltip.tsx
- packages/react/src/stories/Tooltip/Tooltip.stories.tsx
- packages/react/src/types/index.ts
- pnpm-lock.yaml
Fixes :- https://github.com/international-labour-organization/designsystem/issues/534
* Implemented [Popper.js](https://popper.js.org/) to handle the tooltip.
* Modified classes to fix icon
Long tooltip (More than 50 chars)
Normal tooltip (Less than 50 chars)
> fix(react) - Sync tooltip with twig

- .changeset/thirty-steaks-melt.md
- packages/styles/scss/components/_featurecard.scss
- packages/styles/scss/components/_linklist.scss
Fixes :- https://github.com/international-labour-organization/designsystem/issues/716
Notes :- 
* Currently the feature card does not have padding assigned to link in RTL. This needs to be refactored.
Fix :- 
* Add appropriate padding for RTL 
Recording :- 
https://github.com/international-labour-organization/designsystem/assets/32934169/02cda9d7-b600-4c16-b9fb-015f6766ea09
> fix(style) - Feature card RTL link 

- .changeset/metal-horses-promise.md
- packages/styles/scss/components/_navigation.scss
- packages/twig/src/patterns/components/localnav/localnav.twig
- packages/twig/src/patterns/components/navigation/navigation.twig
Fixes :- https://github.com/international-labour-organization/designsystem/issues/740
Notes :- 
* Currently nav and local nav will always display the language selector this needs to be made optional.
Screenshots :- 
Before Big screen
After Big screen
Before Small screen
After Small screen
Before Big screen
After Big screen
Before Small screen
After Small screen
> fix(twig) - Make language selector optional in nav/ local nav

- .changeset/quiet-ears-applaud.md
- packages/twig/src/patterns/components/modal/modal.twig
- packages/twig/src/patterns/components/modal/modal.wingsuit.yml
Fixes https://github.com/international-labour-organization/designsystem/issues/765
* Added aria label attribute to modal in twig.
* **Added modalLabel as an optional param as it would break the existing implementation**
> feat(twig): add aria-label attribute to modal

- .changeset/silly-beans-reflect.md
- packages/styles/scss/components/_tableofcontents.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/771
* Add padding with consideration of the design to prevent overflow between text and arrow
> fix(twig) - Fix padding between arrow and label

- .changeset/mean-apes-check.md
- packages/react/src/components/Dropdown/Dropdown.tsx
- packages/twig/src/patterns/components/dropdown/dropdown.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/766
* Moved option label within the option tag instead of an attribute so that it can be read by screen readers.
> fix(twig/react) - Refactor option label as a child in dropdown

- .changeset/four-experts-allow.md
- packages/styles/scss/components/_richtext.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/773
* Added the same spacing as figure to iframe in richtext component
> fix(style) - Add spacing to iframe in rich text

- .changeset/neat-ducks-flow.md
- packages/react/src/components/Card/Card.tsx
- packages/twig/src/patterns/components/card_detail/card_detail.twig
- packages/twig/src/patterns/components/card_factlist/card_factlist.twig
- packages/twig/src/patterns/components/card_feature/card_feature.twig
- packages/twig/src/patterns/components/card_multilink/card_multilink.twig
- packages/twig/src/patterns/components/card_promo/card_promo.twig
- packages/twig/src/patterns/components/card_stat/card_stat.twig
- packages/twig/src/patterns/components/card_text/card_text.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/769
* Refactor headings of cards from h5 to h3 to ensure headings are in sequential order to improve accessibility.
> fix(react/twig) - Change heading from h5 to h3 in cards

- .changeset/shy-pumas-dream.md
- packages/twig/src/patterns/components/form/formcontrol.twig
https://zoocha.atlassian.net/browse/ILO-631
This change is requested to fix an accessibility issue on the ILO Drupal site.
**Form elements do not have associated label elements**
The label need to be linked to the inputs by the _for_ attribute of the label and the _id/name_ of the input. 
Drupal handles it from different levels, so to add those attributes to the label correctly it need to be printed on its own template.
Adding a block to the label item on the formcontrol.twig (which is used in Drupal for the parent level - form-element.twig) it's possible to print the label inside with their own attributes and still respecting ILO Design system styling.
> feat(twig): Add block to wrap label, as required in Drupal development

- .changeset/pretty-roses-tell.md
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.js
For pages that were rendering breadcrumbs, we had the error like this 
the problem was that the storybook example always renders the context menu, but due to breadcrumbs behavior, the context menu is not required
Here is an example of a breadcrumb component without a context menu, not throwing any errors
https://github.com/international-labour-organization/designsystem/assets/36326203/67f133ae-f242-4381-8186-ae3b8ac539f6
> Breadcrumbs context check

- .changeset/weak-games-promise.md
- packages/styles/scss/components/_accordion.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/785
* Currently the text in the accordion is center aligned on mobile devices
* There is also an issue in RTL where long text overflows the icon
* Aligned text to be at the start of the accordion which supports both LTR and RTL
* Added padding-inline-end instead of traditional padding as it supports RTL as well.
**Iphone SE**
> fix(style) - Refactor alignment on mobile and fix RTL in accordion

- .changeset/eighty-spoons-attack.md
- packages/styles/scss/components/_tag.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/780
* Currently the reset button looks to be off when compared to the other buttons because it has a border.
* Consider the border width when setting the reset button inner padding so that it maintains consistency with other buttons.
> fix(tag) - Refactor reset tag padding to consider border

- .changeset/sweet-feet-grow.md
- packages/styles/scss/components/_pagination.scss
- packages/twig/src/patterns/components/pagination/pagination.wingsuit.yml
Fixes https://github.com/international-labour-organization/designsystem/issues/809
* There is a gap between the forward and end button. The reason this was added is to center the pagination count.
* Remove gap between forward and end button and center the pagination count.
> fix(style) : Remove gap between forward and end button

- .changeset/odd-eggs-camp.md
- packages/styles/scss/components/_breadcrumb.scss
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.twig
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.wingsuit.yml
Breadcrumbs should have 2 types of labels, one that is displayed every time and the second that is inside of the context menu.  The current implementation had no separation for those labels, the main one has a max set of characters, and the context one was using it too. 
This PR creates a separate class for the context label that wraps text.
🔔 `contextmenu` component isn't affected by the issue
> Breadcrumbs text wraping

- .changeset/selfish-cups-vanish.md
- packages/styles/scss/components/_richtext.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/784
* Currently in small widths the ending pullquote and padding is off
**Before** 
**After**
> fix(style) - Ending pullquote missing and padding

- .changeset/famous-pumas-glow.md
- packages/styles/scss/components/_featurecard.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/805
* Currently when the date is hidden in the feature card there is a massive space rather than the expected bottom spacing from the title
* Considered existing padding in the content card and also added spacing for each individual text instead of having it in the link list.
> fix(style) : Adjust spacing when date is not shown

- .changeset/fresh-jars-rule.md
- packages/styles/scss/components/_navigation.scss
#813 interested new logos with standard height, but the varying widths made it so they were still appearing at different heights in the Navigation component.
This sets a standard height on logos in the Nav so that no matter how wide they are, they'll all appear at the same height.
https://github.com/international-labour-organization/designsystem/assets/12401179/dd57ad68-bafa-4446-9b09-28cdb0bc84e8
Uploading Screen Recording 2024-02-20 at 11.22.16.mov…
> Styles: Make logo appear at standard height in nav

- packages/styles/scss/_mixins.scss
- packages/twig/src/patterns/components/hero/hero.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/792
* Currently the tooltip icon is not shown in the hero caption section which breaks the hover as well
* Passed in appropriate prop to display icon
* Removed small gap between caption and hero card
Before
After
> Fix(style) - Tooltip icon not showing on hero caption 

- .changeset/gold-worms-relate.md
- packages/styles/scss/components/_searchfield.scss
- packages/twig/src/patterns/components/search/index.js
- packages/twig/src/patterns/components/search/search.behavior.js
- packages/twig/src/patterns/components/search/search.js
- packages/twig/src/patterns/components/search/search.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/708
* Currently there is no clear button in the search textfield
* Add X icon to search field when text is entered
> feat(twig) - Add clear button to search

- .changeset/many-mails-punch.md
- .changeset/neat-trains-study.md
- contributing.md
- package.json
- packages/twig/src/patterns/components/button/button.twig
- packages/twig/src/patterns/components/tableofcontents/tableofcontents.twig
- packages/twig/src/patterns/components/tableofcontents/tableofcontents.wingsuit.yml
This fixes #604 
This was caused by problems stemming from how icons were handled in the Twig package (described in #692). The root issue was eventually resolved in #829, however the Table of Contents still wasn't rendering the close icon in its mobile view correctly. 
There were two reasons for this:
1. The underlying Button component wasn't passing the right properties for the new Icon component
2. The ToC wasn't passing the right properties to the Button component
In fact, the Table of Content component was actually letting the user pass any properties to the Open & Close buttons that they wanted. This was especially problematic given that the Buttons will only work if they have a specific classname. The user shouldn't have to figure out what that classname is or be able to set it …
> Twig: Fix Table of Contents close button not showing on mobile

- .changeset/nervous-lies-return.md
- packages/themes/tokens/fonts/base.json
Add Hiragino Sans and Yu Gothic as fallbacks for Noto Sans CJK JP (Japanese)
Fixes #818
> Fix(themes): add fallbacks for Japanese fonts

- .changeset/friendly-suits-press.md
- packages/twig/src/patterns/components/card_multilink/card_multilink.twig
Fix bug in Multilink Card that prevented `alignment` property from being applied was size was set to `fluid`.
> Fix/Twig: multilink card alignment bug

- .changeset/healthy-badgers-sneeze.md
- packages/styles/scss/components/_tableofcontents.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/847
* Currently when table of content is hovered on in small screens the padding changes
* Have the padding-inline-end for hover state as well
> fix(style) - table of contents padding on hover

- .changeset/shy-frogs-drop.md
- packages/styles/package.json
- packages/styles/postcss.config.js
- pnpm-lock.yaml
This PR removes legacy build tooling for the `@ilo-org/styles` package and makes `build:next` default 
- removed extra packages: `postcss`, `postcss-cli`, `cssnano` those packages are contained inside the gulps implementation
- `postcss` config is not removed, because `gulp-postcss` needs it, but the bare config is enough because `cssnano` is handled by gulpfile 
-  extra unused commands were removed
ILO Drupal website has no dependency on legacy implementation. The styles are mentioned inside `library` and `theme` and both of them are using `css` dir
> ilo.libraries.yml
```yml
global:
css:
base:
dist/css/00-base/base.css: {}
node_modules/@ilo-org/styles/css/global.css: {}
node_modules/@ilo-org/styles/css/components/container.css: {}
```
> ilo.theme
```php
function …
```
> Deprecated build directory for styles 

- .changeset/nervous-weeks-cross.md
- packages/twig/src/patterns/components/tabs/tabs.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/845
* Currently the lighthouse accessibility check is throwing an error that mentions [aria-*] attributes do not match their roles in tabs
* Assign proper roles and aria attributes for the tabs component
> fix(twig) - Tabs attributes do not match their roles

- .changeset/chilly-eggs-heal.md
- packages/twig/src/patterns/components/accordion/accordion-item.twig
- packages/twig/src/patterns/components/accordion/accordion.js
- packages/twig/src/patterns/components/accordion/accordion.wingsuit.yml
This PR adds accessibility features to the accordion component 
https://github.com/international-labour-organization/designsystem/assets/36326203/62b1bcd4-3df1-4808-81a8-8fc73ec5369c
At first, I tried to implement a11y feature following [W3C's ARIA Authoring Practices Guide (APG)](https://www.w3.org/WAI/ARIA/apg/patterns/accordion/examples/accordion/), this method utilizes the `hidden` HTML attribute which is equivalent of `display: none`, the implementation was almost full. Still, we have an animation effect for the accordion, but hidden elements can't be animated so I moved on. 
The current implementation leverages JS, during mounting + open/close events and we dynamically trigger tab indexes.  implementation tweaks only focusable elements.
- Template is much more readable now
- Initial …
> Accordion a11y

- .changeset/perfect-rules-rescue.md
- packages/react/src/components/Pagination/Pagination.tsx
- packages/styles/scss/components/_pagination.scss
- packages/twig/src/patterns/components/pagination/pagination.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/868
* Currently the pagination breaks when we switch to RTL mode. 
* Add proper spacing between page count
* Fix RTL text of page count and mirror spacing
> fix(twig/react) - Pagination in RTL

- .changeset/seven-ducks-rescue.md
- packages/react/.storybook/preview-head.html
- packages/react/.storybook/preview.tsx
Fixes https://github.com/international-labour-organization/designsystem/issues/357
* Currently there is no padding set in stories and padding is set to 0
* Add parameter layout padded
* Remove padding reset to 0
> fix(react) - add paramater layout to storybook

- .changeset/six-bikes-decide.md
- packages/react/package.json
- packages/react/rollup.config.mjs
We need to start from the beginning to understand the root of the problem. React package is exported in two types
- CJS: aka `commonjs`  aka nodes in initial module system
```js
module.exports  // "default" export
exports.something // "named" exports
```
- ESM: [ECMA Specification](https://tc39.es/ecma262/#sec-modules), what are modules for Javascript as a language aka *The Correct Way*
```js
export default  // default export
export { something } // named export
```
Here is our rollup config
```js
// rollup.config
const config = {
...,
output: [
{
dir: "lib/esm",
format: "esm",
},
{
dir: "lib/cjs",
format: "cjs",
},
],
}
```
We know our target bundle types, but here is a catch we are writing the ESM in our codebase but rollup has to target both
ESM and CJS. Just imagine the compilation …
> Explicit auto exports

- .changeset/gentle-steaks-retire.md
- packages/styles/scss/components/_richtext.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/870
* Currently the corner cut in the pullquote card is not transparent
* Use cornercut mixin 
* Sync with design on sizing
> fix(style) - make cornercut transparent in pullquote

- .changeset/poor-spiders-juggle.md
- packages/styles/scss/components/_richtext.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/381
* Currently the heading styles are swapped for mobile and desktop
* Add proper heading styling for mobile and desktop
> fix(style) - Refactor incorrect heading styles in richtext

- .changeset/modern-mugs-lay.md
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/878
* Currently in large devices the breadcrumb items in the middle have a different font style.
* Add styling to all the link labels in the breadcrumb
> fix(style) - refactor link styles in breadcrumb

- packages/react/.storybook/preview.tsx
Fixes https://github.com/international-labour-organization/designsystem/issues/898
* Currently when the react storybook loads up it defaults the direction selected to RTL
* Set default value to false to default to LTR
> docs(react) - Make LTR default in storybook

- .changeset/stupid-clocks-pull.md
- packages/twig/src/patterns/components/modal/modal.js
- packages/twig/src/patterns/components/navigation/navigation.js
This PR addresses the unsafe event listeners in the modal and navigation components. Those might be issues of `ilo_base_theme`, as mentioned in #931 comment, but, in case of incorrect props or removed dom elements, those event listeners now have a safety net
https://github.com/international-labour-organization/designsystem/assets/36326203/d0a39f31-800f-4aa7-bf63-f8f8ccc10e7d
> Safe Event Listeners

- .changeset/real-keys-fetch.md
- packages/react/copystyles.js
- packages/react/package.json
- pnpm-lock.yaml
Fixed #762 
Added a build script that copies the CSS files from the style package to the build output of the React package. Now styles can be imported directly from the React package as so.
```
import '@ilo-org/react/styles/index.css'
```
```
import '@ilo-org/react/styles/components/accordion.css'
```
Also added and tested the exports definition for the new styles folder from a vite project. It works as expected.
> GH-762: exported styles from the react package

- .changeset/twelve-ducks-look.md
- packages/styles/scss/components/_tabs.scss
https://zoocha.atlassian.net/browse/ILO-253
This is to amend this requirement:
Text always shows in one line. Text truncates according to screen size.
> feat(styles): Content tabs titles always in one line

- .changeset/few-lions-join.md
- packages/styles/scss/components/_accordion.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/936
* Currently in large screens the accordion overflows with the plus icon. 
* Based on investigation the spacing used is also not in sync with the design. 
* The design uses 44px spacing from the end
Large screen (Large Accordion) :- 
Small screen (Large Accordion) :-
Large screen (Small Accordion) :- 
Small screen (Small Accordion) :-
* Sync with design and add appropriate spacing for padding-inline-end
> fix(style) - add appropriate spacing to accordion text

- .changeset/funny-teachers-remember.md
- packages/styles/scss/_mixins.scss
- packages/styles/scss/components/_hero.scss
#820 introduced a regression that broke responsive layouts in the Hero component. 
This reverts back to the former version of the Hero component and adds a fix for the issue it was intended to solve, making sure the breadcrumb appears correctly in mobile.
> Fix broken hero layouts in mobile

- .changeset/breezy-dryers-sit.md
- packages/styles/scss/components/_navigation.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/929
* The corner of the language switcher button looks a bit unaligned with the cut. 
* Refactor clipcut to make button edge less sharp
> fix(style) - reduce sharpness of language switcher button

- .changeset/sharp-icons-eat.md
- packages/styles/scss/components/_breadcrumb.scss
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/950
* Currently the text in breadcrumb links overflow in small devices
* This makes both the fixes compatible https://github.com/international-labour-organization/designsystem/pull/894 and https://github.com/international-labour-organization/designsystem/pull/815
* Add text styles to dropdown
* Refactor classnames for labels
> fix(style) - breadcrumb links not wrapping correctly

- .changeset/tidy-houses-worry.md
- packages/styles/scss/components/_tabs.scss
This does the same thing as #939 but with better supported css. It seems like the previous solution used some `-webkit` properties that are not well supported.
> Fix/styles: tabs on one line

- .changeset/mighty-dancers-study.md
- packages/fonts/font-css/fonts-ar.css
Arabic font face declarations were set incorrectly so that bond fonts were being applied even when the font-weight was set to normal. This fixes that by setting the appropriate font-weight value to the bold fonts.
https://www-preview.ilo.org/ar/alraq
> Fix/Fonts: Arabic font weights

- .changeset/chilly-pants-glow.md
- .changeset/tidy-ties-work.md
- packages/styles/scss/components/_tabs.scss
- packages/twig/src/patterns/components/tabs/tabs.twig
- packages/twig/src/patterns/components/tabs/tabs.wingsuit.yml
Fixes https://github.com/international-labour-organization/designsystem/issues/953
* Currently tabs are not showing icons in twig
* Added new icon component passing icon name
*  Used sizing given by design
> fix(twig) - use new icon component in tabs

- packages/react/src/stories/Logo/Logo.stories.tsx
- packages/react/src/stories/LogoGrid/LogoGrid.stories.tsx
- packages/twig/src/patterns/components/logogrid/logogrid.wingsuit.yml
Fixes https://github.com/international-labour-organization/designsystem/issues/955
* Currently logogrid component is under **brand** category it needs to be moved to **media**
> docs(react/twig) - move logo grid from brand to media category

- .changeset/new-wasps-smash.md
- .changeset/silly-pumas-smoke.md
- packages/styles/scss/_mixins.scss
- packages/styles/scss/components/_breadcrumb.scss
- packages/styles/scss/components/_contextmenu.scss
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.js
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.twig
- packages/twig/src/patterns/components/breadcrumb/breadcrumb.wingsuit.yml
- packages/twig/src/patterns/components/contextmenu/contextmenu.twig
I set out to fix #972 while at the same time contributing to #971 and cleaning up the CSS. I ended up doing a complete refactor of the both the Twig and SCSS component. It also solves an accessibility issue wherein that were supposed to be hidden in the context menu were still clickable and accessible via tab navigation
I'll finish this up tomorrow and implement in React as well. In the meantime, comments welcome.
> Twig/React/Styles: Refactor Breadcrumb

- .changeset/selfish-sheep-battle.md
- packages/twig/copystyles.js
- packages/twig/cypress.config.js
- packages/twig/cypress/e2e/card.cy.js
- packages/twig/cypress/support/commands.js
- packages/twig/cypress/support/e2e.js
- packages/twig/docker-compose.yml
- packages/twig/package.json
- pnpm-lock.yaml
A part of #947.
This PR adds the basic setup for running tests against the twig base theme container locally.
Current issues
- The base theme copies index.css directly from the styles packages while not declaring the styles package as an explicit dependency. It should be changed to copy index.css from the twig package. Previously, the twig package was not exporting the correct CSS file with all the styles for the components. I fixed that in this PR.  (Raised https://github.com/international-labour-organization/ilo_base_theme/issues/11 to resolve)
- The base theme image has caching enabled and the cache needs to be manually cleared whenever the twig components are changed for those changes to be visible on the theme site. We should probably disable the cache in the image since the image …
> test(twig): added local cypress setup

- .changeset/hot-avocados-appear.md
- packages/styles/scss/components/_accordion.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/981
* Currently when the accordion opens up the padding inside changes which breaks the sentence.
* Add consistent padding inside the panel
https://github.com/international-labour-organization/designsystem/assets/32934169/f5930369-dc85-4918-a5f3-939f37ec53da
> fix(style) - refactor padding inside accordion panel

- .changeset/honest-birds-juggle.md
- packages/react/src/components/SocialMedia/SocialMedia.args.ts
- packages/react/src/components/SocialMedia/SocialMedia.props.ts
- packages/react/src/components/SocialMedia/SocialMedia.tsx
- packages/styles/scss/components/_socialmedia.scss
- packages/twig/src/patterns/components/socialmedia/socialmedia.twig
- packages/twig/src/patterns/components/socialmedia/socialmedia.wingsuit.yml
Fixes https://github.com/international-labour-organization/designsystem/issues/956
* Add a new icon size option to change the size of social media icons
Normal 
Large
> feat(react/twig): add icon size option to social media

- .changeset/wild-moose-explode.md
- packages/styles/scss/components/_richtext.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/773
* Add spacing to iframe in richtext
* Revert all changes done before
* Add appropriate spacing to iframe
> fix(style) - Add spacing to iframe in richtext 

- .changeset/itchy-spies-sparkle.md
- packages/styles/scss/components/_accordion.scss
Fixes https://github.com/international-labour-organization/designsystem/issues/843
* Refactor styles of accordion expanded status
Demo :- 
https://github.com/international-labour-organization/designsystem/assets/32934169/c71976b6-d142-48c0-8d12-dff5f8497e6c
> fix(style) - improve accordion expanded status

- .github/workflows/test.yml
- packages/twig/package.json
- pnpm-lock.yaml
Fixed #947
This PR makes the cypress tests for twig run within the test workflow. To do this, it spins up a docker container using the ilo base theme image and overwrites the build artifacts inside the image with the artifacts generated in the workflow.  It then runs the cypress tests against this container.
I also updated the version of all the actions that are being used in the workflow and fixed the caching of pnpm dependencies. It drops the matrix runner since Mac OS runners don't support running docker.
> ci(github): added twig cypress tests to test workflow

- .github/workflows/test.yml
Fixes #1052 
The error seems to have been caused by mismatching caching strategies between the pnpm dependencies and cypress. This results in cases where there is a cache hit for pnpm dependencies but a cache miss for the cypress binary. Since there was a cache hit for the dependencies, pnpm will not bother downloading the cypress binary - hence the error message.
This PR changes the caching strategy for the cypress binary to match the caching strategy for the pnpm dependencies so that the situation above does not occur.
> ci(github): fixed the cypress binary missing error

- packages/twig/cypress/e2e/transitions/loading.cy.js
- packages/twig/cypress/e2e/user-interface/button.cy.js
- packages/twig/cypress/e2e/user-interface/icon.cy.js
- packages/twig/cypress/e2e/user-interface/read-me.cy.js
- packages/twig/cypress/e2e/user-interface/tabs.cy.js
- packages/twig/cypress/e2e/user-interface/tags.cy.js
Initial implementation of user interface :- 
* Create tests for user interface rendering
* Create test for transitions
> test(twig) - add initial tests for user interface/ transitions

- .changeset/chilled-melons-whisper.md
- .changeset/chilly-pants-juggle.md
- packages/react/src/components/Button/Button.tsx
- packages/styles/scss/components/_button.scss
- packages/styles/scss/components/_icon.scss
- packages/styles/scss/components/index.scss
- packages/styles/scss/theme/_foundation.scss
- packages/twig/src/patterns/components/button/button.twig
- packages/twig/src/patterns/components/icon/icon.twig
This PR provides refactoring/housekeeping of the **button** component.
Related to #971 
**Design bugs fixed :-** 
**Align the small button icon and label**
Before :- 
After :- 
**Fix icon only component in twig**
Before :- 
After :-
> fix(style) - housekeeping for button css

- packages/maestro/package.json
This adds aliases for the `build:lib` and `build:docs` scripts that get run by turborepo on all packages when we run those two commands. Without this you have to build maestro separately, which isn't ideal, it should get build with everything else in both scenarios: building the library and building the Storybook projects.
> fix(maestro): add monorepo build scripts

- packages/maestro/src/plugin/twig.d.ts
- packages/maestro/src/plugin/twig.js
- packages/maestro/src/vite.ts
As mentioned in #1111, Mastro was unable to process the component that had imports like this 
```twig
{% include '@components/' ~ component ~ '/' ~ component ~ '.twig' with modaldata %}
```
The problem was that `vite-plugin-twig-drupal,` which is used under Maestro's hood, does not implement parsing the dynamic imports.
This PR allows Maestro to support imports like this.
During the Maestro's integration, we have a new option named `dynamics`. This is a string array that should contain all component names that are using a dynamic import. 
```ts
export default defineConfig({
plugins: UIPatterns({
namespaces: {
components: join(__dirname, "..", "src/components"),
},
globals: {
prefix: "ilo",
},
dynamics: ["modal", "tabs"],
}),
});
```
This helps the maestro prevent `cross-dynamic` imports. …
> Twig Dynamic Imports

- packages/twig-new/.eslintrc.cjs
- packages/twig-new/.gitignore
- packages/twig-new/package.json
- packages/twig-new/src/components/modal/modal.component.yml
- packages/twig-new/src/components/search/search.js
- packages/twig-new/src/components/tooltip/tooltip.js
- packages/twig-new/stories/card_data.stories.js
- pnpm-lock.yaml
Fixes #1116 
This PR restores all the fields in package.json to be similar to the old twig package. Since the lint commands did not run without the config, this PR also restores and adapts the ESLint config and fixes the lint errors that it found.
⚠️ This should probably be merged just before the old twig package is removed. This PR assumes that several scripts will be added in other PRs.
> build(twig): restored package.json fields

- .github/workflows/test.yml
This PR uses a preview Docker image for the base theme built on https://github.com/international-labour-organization/ilo_base_theme/pull/28 
Once we are ready to merge and release the big Twig refactoring, we must remember to change it back to `0.x`.
> chore(twig): use base theme preview docker image

- packages/maestro/src/generator/create.ts
Fixes https://github.com/international-labour-organization/designsystem/issues/1143
**Note :-** 
* Currently Maestro sets the components to be centered.
**Fix :-** 
* Layout should be changed to padded instead as it gives more space for the component to fit
**Screenshot :-**
> Twig Docs: Story containers are too narrow

- .changeset/green-roses-lick.md
- packages/twig/src/components/breadcrumb/breadcrumb.js
- packages/twig/src/components/breadcrumb/breadcrumb.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/1144
Note :- 
* Fixed the breadcrumb not rendering middle links
* Refactored from items to links. (Same as react)
Screenshot
> Twig: Breadcrumb isn't rendered correctly in new Storybook

- .changeset/neat-berries-pretend.md
- .changeset/short-dingos-repair.md
- packages/twig/rollup.config.js
Creating a `2.0` for only the filename change will be a bit overkill; since we haven't introduced any `specification` change for the pattern definition file, we can also export `*.wingsuit.yml` files to support `1.x`
> Wingsuit export 

- packages/twig/docker-compose.yml
* Pin CI to use specific base theme version. This is to prevent changes in the base theme from breaking the build pipeline in the design system.
> chore(twig) - pin tests to specific base theme version

- .changeset/thick-feet-retire.md
- packages/react/src/components/Cards/CardGroup/CardGroup.tsx
- packages/twig/src/components/cardgroup/cardgroup.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/1182
* Refactor cardgroup to use the button component directly instead of using css classes.
> fix(react-twig): refactor cta to use button component

- .changeset/blue-flies-report.md
- packages/react/src/components/Cards/MultilinkCard/MultiLinkCard.tsx
- packages/styles/scss/components/_multilinkcard.scss
- packages/twig/src/components/card_multilink/card_multilink.twig
Fixes https://github.com/international-labour-organization/designsystem/issues/864
* Make image optional in multilink card
* Add max-width to wide and fluid when image is available.
> fix(twig): make image optional in multilink card

- .github/workflows/release.yml
When the node version was update, we accidentally forgot to update the version name in the Github action step. This remove the version entirely from the step name since we don't really need it.
> ci(github): removed outdated version name

- .changeset/fast-elephants-drum.md
- packages/twig/cypress/e2e/navigation/breadcrumb.cy.js
- packages/twig/src/components/breadcrumb/breadcrumb.twig
> fix(twig): breadcrumb showing the last element twice

- .changeset/ninety-cycles-cough.md
- packages/twig/cypress/e2e/navigation/social-media.cy.js
- packages/twig/cypress/fixtures/socialmedia.json
- packages/twig/src/components/socialmedia/socialmedia.twig
This adds backward compatibility to the socialmedia component which in 1.1.1 removed the twitter icon and replaced it with X. With this, passing `twitter` to as an argument to the icon field will render an X icon.
Before merging it, we need to add some tests to the social media component. However, the tests that we have now are really testing the component, they're testing the arguments passed to the component from patterns, which is wrong.
I tried to update the tests using the ilo_base_theme pattern preview, but was unable. I've opened [#34](https://github.com/international-labour-organization/ilo_base_theme/issues/34) in that repo to track.
> Fix(Twig): backwards compatibility for social media component

- package.json
`pnpm clean:deps` was removing a `pnpm-lock.yaml` file that resolves to broken dependencies
> Prevent Lockfile Removal

- .changeset/healthy-foxes-beam.md
- packages/twig/cypress/e2e/cards/data-card.cy.js
- packages/twig/src/components/card_data/card_data.component.yml
- packages/twig/src/components/card_data/card_data.twig
From a developer of ilo.org: 
“We need a change in the Design System, so that in card_data.twig we pass target: item.target when looping through dataset.files.items to build the file download buttons. This way we can pass “_blank” for PDFs.”
This corrects this issue and includes some tests to make sure it works.
> Hotfix: Data Cards can pass a `target` to file buttons

- .changeset/cold-cars-sing.md
- packages/react/src/components/LinkList/LinkList.tsx
- packages/styles/scss/_mixins.scss
- packages/styles/scss/components/_accordion.scss
- packages/styles/scss/components/_blockquote.scss
- packages/styles/scss/components/_callout.scss
- packages/styles/scss/components/_linklist.scss
- packages/styles/scss/components/_pagination.scss
- packages/styles/scss/components/_tabs.scss
- packages/styles/scss/components/_tag.scss
- packages/twig/cypress/e2e/navigation/link.cy.js
- packages/twig/cypress/e2e/navigation/pagination.cy.js
- packages/twig/src/components/accordion/accordion-item.twig
- packages/twig/src/components/linklist/linklist.twig
This PR introduces a new mixin that supports base64 icon placement with new theme support (#999)
The API for the new mixin is almost the same, to maintain the same DX 
```scss
@include icon("chevron_right", var(--ilo-color-blue));
```
1. The icon machine name from `@ilo-org/icon`, `required`
2. The CSS variable that indicates the color of the icon
Base64 encoded `svg` has no direct support for CSS variables since it is evaluated as a static string,  one possible solution to get rid of `dataurilicon` was to eliminate the base64 encoded svgs but it has its disadvantages
- We are maintaining two design systems for `react` and for `twig` and having a single source of truth from the styles package is a good thing
- We could use the `icon` component for both `twig` and `react,` but for `twig` …
> New Icon Mixin

- .changeset/gold-pillows-wait.md
- packages/twig/cypress/e2e/navigation/link.cy.js
- packages/twig/src/components/localnav/localnav.behavior.js
- packages/twig/src/components/navigation/navigation.js
This PR fixes the responsive "burger menu" error that was introduced during `localnav` migration from `wingsuit` to `maestro`
https://github.com/user-attachments/assets/8f9339c0-8c69-4281-adeb-ba6c9b8f1576
`navigation.scss` file contains a big overhead and we have an open issue about it #823, but the subject is a bit more complex. Despite `navigation.scss` being the complex implementation that is too big to be a "component" it also contains the styles for `localnav` and also `localnav` isn't working without the Behavior file from the `Navigation` component, so this 2 components are deeply intertwined, after finishing the #823 we should open the follow-up ticket for `localnav` separation
> Localnav responsive menu

- .changeset/little-needles-sit.md
- packages/styles/scss/components/_tabs.scss
This PR adds an improvement suggested by [#1244](https://github.com/international-labour-organization/designsystem/issues/1244)
- The UX improvements are done and tested
- Secondary tabs CSS are added for the `base_theme`  but we don't have the concept of `secondary` tabs in the design yet
> Tabs Improvent

- .changeset/modern-carrots-visit.md
- packages/twig/cypress/e2e/cards/data-card.cy.js
- packages/twig/cypress/e2e/cards/fact-list-card.cy.js
- packages/twig/cypress/fixtures/datacard.json
- packages/twig/src/components/card_data/card_data.component.yml
- packages/twig/src/components/card_data/card_data.twig
Data Card should only render in two columns if `size` is set to `narrow` or `wide`
Fixes #1270
> Fix(twig): data card size and columns.

- packages/twig/package.json
While testing the Twig package, it periodically becomes necessary to clear the Drupal cache of the base theme to make sure that you're testing the most recent build assets. This is done via a straightforward docker compose command:
```
$ docker exec twig-backend-1 drush cache-rebuild
```
However, it's annoying to have to type the whole thing and I kept forgetting the name of the docker container, so I add a simple script to package.json
```
pnpm --filter twig cr:theme
```
which does the same thing.
> Twig: add script to clear base theme cache

- .changeset/long-tips-listen.md
- packages/twig/src/components/card/card.component.yml
This fixes a bug I noticed in the Twig Storybook whereby the Card component wasn't rendering the correct variant.
You can see this by looking at the [Data Variant](https://twig.ui.ilo.org/?path=/story/components-cards-card--data) on Storybook, which incorrectly renders the Multi-link Card instead.
I managed to correct this simply by removing the `basic` variant. Given that we don't have a `basic` card and that it doesn't use a `type` setting, I don't think it should have been there in the first place.
> Fix(Twig): remove basic variant from card pattern definition

- .changeset/red-fishes-kiss.md
- packages/react/src/components/LanguageToggle/LanguageToggle.tsx
- packages/react/src/components/LanguageToggle/index.ts
- packages/react/src/components/index.ts
- packages/react/src/stories/LanguageToggle/LanguageToggle.stories.tsx
- packages/styles/scss/components/_languagetoggle.scss
- packages/styles/scss/components/index.scss
This PR introduces a new `LanguageToggler` component. It's a generic implementation that can be used across all three implementations right now 
https://github.com/user-attachments/assets/9f5c34e4-db20-4966-9b34-2cab1f1c83b3
The new codewise components look like this
```jsx
<LanguageToggle
language="English"
options={[
{
label: 'Spanish',
url: '#'
},
{
label: 'German',
url: '#'
},
{
label: 'French',
url: '#'
}
]}
/>
```
- It respects the theme
- It allows you to hide the `globe` icon, with the `hideIcon` prop
- It uses the native context menu as the breadcrumb
- It allows you to pass all props to the native `div` element 
The styles are done with the #999 rules. It utilizes the CSS variables + new foundation and new `icon` mixin. Background color is implemented via component variables so …
> Language Toggler 

- .changeset/angry-spoons-provide.md
- .changeset/dull-teachers-allow.md
- packages/react/src/components/LanguageToggle/LanguageToggle.tsx
- packages/react/tests/LanguageToggle.test.tsx
- packages/styles/scss/components/_languagetoggle.scss
This fixes some minor accessibility issues that prevented the LanguageToggle from being used with tab navigation.
Adapts some classnames to the modified BEM convention we use in the rest of the project
This adds a suite of tests for most component functionality
> Fix(Styles): LangToggle a11y isues and BEM formatting

- .changeset/khaki-dryers-grab.md
- .changeset/long-mirrors-repair.md
- .github/workflows/canary.yml
- packages/react/src/components/Button/Button.tsx
- packages/react/src/components/Cards/DataCard.tsx
- packages/react/src/components/Cards/TextCard.tsx
- packages/react/src/components/Dropdown/Dropdown.props.ts
- packages/react/src/components/Dropdown/Dropdown.tsx
- packages/react/src/components/Tabs/Tabs.props.ts
- packages/react/src/components/Tabs/Tabs.tsx
- packages/react/src/components/TextInput/TextInput.props.ts
- packages/react/src/components/TextInput/TextInput.tsx
- packages/react/src/components/index.ts
- packages/react/src/types/index.ts
- packages/styles/scss/components/_linklist.scss
This PR introduces the changes done in the canary branch for the @ilo-org/react and @ilo-org/styles packages.
- Value prop for the `TextInput` component
- Width for link-list label
- Submit prop for the `Button` component
- `DataCard` can recive `copy` as ReactNode
- `Dropdown` can recive default value
- `className` support for `Tabs`
> Canary Batch

- .changeset/many-apricots-know.md
- .changeset/perfect-bats-shop.md
- .changeset/stale-trains-listen.md
- packages/react/src/components/Profile/Profile.tsx
- packages/react/src/components/Tabs/Tabs.args.tsx
- packages/react/src/components/Tabs/Tabs.props.ts
- packages/react/src/components/Tabs/Tabs.tsx
- packages/react/src/stories/Profile/Profile.stories.tsx
- packages/react/src/stories/Tabs/Tabs.stories.tsx
- packages/react/tests/Profile.test.tsx
- packages/react/tests/Tabs.test.tsx
- packages/styles/scss/components/_profile.scss
- packages/styles/scss/components/_tabs.scss
- packages/styles/scss/theme/_foundation.scss
- packages/twig/cypress/e2e/user-interface/tabs.cy.js
- packages/twig/cypress/fixtures/tabs.json
- packages/twig/src/components/tabs/tabs.component.yml
- packages/twig/src/components/tabs/tabs.js
- packages/twig/src/components/tabs/tabs.twig
- This implements the `dark` theme in both Twig and React. 
- The stylesheets for the Tab component got refactored and simplified quite a bit in the process
- Adds a bunch of tests in both React and Twig
- Fixes #1351 
👉 [Link to test](https://deploy-preview-1386--ilo-ui-react.netlify.app/?path=/story/components-user-interface-tabs--default&args=theme:dark)
- Puts the finishing touches on the Dark theme which was already mostly implemented already
- Adds a bunch of tests in both React and Twig
- Fixes #1336 
👉 [Link to test](https://deploy-preview-1386--ilo-ui-react.netlify.app/?path=/story/components-content-profile--default&args=className:storybook;role:ILO+Director-General;theme:dark&globals=backgrounds.value:!rgba(35,0,80,1))
> React/Twig: Dark Theme for Tabs and Profile

- .changeset/warm-berries-rescue.md
- packages/react/src/components/Callout/Callout.tsx
- packages/react/src/stories/Callout/Callout.stories.tsx
- packages/react/tests/Callout.test.tsx
- packages/styles/scss/components/_callout.scss
- packages/twig/cypress/e2e/feedback/callout.cy.js
- packages/twig/cypress/fixtures/callout.json
- packages/twig/src/components/callout/callout.js
- packages/twig/src/components/callout/callout.twig
Fixes some issues to the Callout component including wrong background text for `info` state. Also refactors the css to use the correct modified bem convention.
> fix(react/twig/styles): refactor callout

- packages/twig/cypress/e2e/utils/statefulComponent.cy.js
- packages/twig/src/utils/statefulComponent.js
This PR proposes a utility class to the Twig package called `StatefulComponent`. It provides simple reactive state system that triggers handlers automatically when state changes.
While working on #823, I noticed that the Navigation component has to manage a bunch of state (whether the mobile drawers are open are closed in desktop or mobile where there are more than one). There are several others components like LanguageToggle and Breadcrumb that have to manage state as well, albeit it a little less. 
We have tickets open for new components like a photogallery that might have to manage a lot more state.
At the same time, I really like that the Twig package is lightweight in terms of JavaScript. We've done a good job of "just using the platform" wherever possible and I think we should …
> Feat(Twig): StatefulComponent

- .changeset/cool-toys-nail.md
- packages/react/src/components/LanguageToggle/LanguageToggle.tsx
- packages/react/src/components/Nav/MainNav.tsx
- packages/react/tests/MainNav.test.tsx
- packages/react/vitest.setup.ts
- packages/styles/scss/components/_languagetoggle.scss
- packages/styles/scss/components/navigation/_nav-main.scss
- packages/styles/scss/components/navigation/internal/mobile/_nav-mobile.scss
- packages/twig/cypress/e2e/navigation/nav.cy.js
- packages/twig/jsconfig.json
- packages/twig/src/components/nav/desktop/navmenu.twig
- packages/twig/src/components/nav/desktop/navsearch.twig
- packages/twig/src/components/nav/mobile/mobiledrawer_main.twig
- packages/twig/src/components/nav/nav.component.yml
- packages/twig/src/components/nav/nav.js
- packages/twig/src/components/nav/nav.twig
- packages/twig/src/components/nav/nav_compact.twig
- packages/twig/src/components/nav/nav_complex.twig
- packages/twig/src/components/nav/nav_main.twig
- packages/twig/stories/nav.stories.js
⚠️  Merge after #1647 
This PR introduces a new  main-nav component for the `twig` design system
https://github.com/user-attachments/assets/8615189b-a48e-4d8e-929d-3d14070dc098
https://github.com/user-attachments/assets/87106eff-be60-4d6f-bbe6-93cc1269a6a5
New search is implemented inside of `navsearch.twig` and JS bundle is reworked to allow use of both drop-downs, double open collision  is also handled. Search functionality is handled with the same `form` component so migration should not cause many problems, search fields also have dedicated selector to target them with ease 
All styles are shared, only 4 lines of css is dedicated to twig to handle the form sizing
> Twig: main-nav component
