package.json
pnpm-lock.yaml

In a vain attempt to fix breaking builds on Netlify.

Bump turborepo

---

packages/fonts/index.scss

Semibold was being used as the font file for weight 700

fix(Fonts): Fix the bold reference

---

packages/styles/scss/_mixins.scss
packages/themes/tokens/widths/base.json

Match design feedback for border width and color

bugfix(Link): fix colors and border

---

packages/react/src/__tests__/ContextMenu.test.tsx
packages/react/src/__tests__/__snapshots__/Storyshots.test.js.snap
packages/react/src/components/ContextMenu/ContextMenu.args.ts
packages/react/src/components/ContextMenu/ContextMenu.props.d.ts
packages/react/src/components/ContextMenu/ContextMenu.tsx
packages/react/src/components/ContextMenu/index.ts
packages/react/src/stories/ContextMenu.stories.tsx
packages/styles/scss/components/_contextmenu.scss
packages/styles/scss/components/index.scss
packages/themes/tokens/brand/base.json
packages/themes/tokens/color/_base.json
packages/themes/tokens/spacing/tooltip.json
packages/twig/src/patterns/components/contextmenu/contextmenu.stories.jsx
packages/twig/src/patterns/components/contextmenu/contextmenu.twig
packages/twig/src/patterns/components/contextmenu/contextmenu.wingsuit.yml
packages/twig/src/patterns/components/contextmenu/index.js

This adds the Context Menu, which is a sort of sub-component used by others components like the Breadcrumb.
https://bluestate.atlassian.net/browse/IDS-14

Issue/ids 14/context menu

---

packages/react/src/stories/Accordion.stories.tsx
packages/twig/src/patterns/components/accordion/accordion-item.twig
packages/twig/src/patterns/components/accordion/accordion.js
packages/twig/src/patterns/components/accordion/accordion.stories.jsx
packages/twig/src/patterns/components/accordion/accordion.wingsuit.yml

@ghlost Here's an example of variants with differing fields in the Accordion.

feat(Accordion): add variations to Twig Storybook for Accordion

---

packages/react/src/components/Button/Button.props.d.ts
packages/react/src/components/Button/Button.tsx
packages/react/src/types/index.ts
packages/styles/scss/components/_button.scss
packages/styles/scss/components/_modal.scss
packages/styles/scss/components/index.scss
packages/twig/images/.gitignore
packages/twig/importsvgs.js
packages/twig/package.json
packages/twig/src/namespaces.js
packages/twig/src/patterns/components/button/button.twig
packages/twig/src/patterns/components/button/button.wingsuit.yml
packages/twig/src/patterns/components/icon/icon.twig
packages/twig/src/patterns/components/icon/index.js
packages/twig/src/patterns/components/modal/index.js
packages/twig/src/patterns/components/modal/modal.behavior.js
packages/twig/src/patterns/components/modal/modal.js
packages/twig/src/patterns/components/modal/modal.stories.jsx
packages/twig/src/patterns/components/modal/modal.twig
packages/twig/src/patterns/components/modal/modal.wingsuit.yml
pnpm-lock.yaml

This adds the Twig version of the modal.
https://bluestate.atlassian.net/browse/IDS-65

Issue/ids 65/modal

---

packages/react/src/components/Tooltip/Tooltip.props.d.ts
packages/react/src/components/Tooltip/Tooltip.tsx
packages/styles/scss/components/_tabs.scss
packages/styles/scss/components/_tooltip.scss
packages/styles/scss/components/index.scss
packages/twig/apps/storybook/preview-head.html
packages/twig/src/patterns/components/button/button.wingsuit.yml
packages/twig/src/patterns/components/polyfill/index.js
packages/twig/src/patterns/components/polyfill/polyfill.twig
packages/twig/src/patterns/components/tabs/index.js
packages/twig/src/patterns/components/tabs/tabs.behavior.js
packages/twig/src/patterns/components/tabs/tabs.js
packages/twig/src/patterns/components/tabs/tabs.stories.jsx
packages/twig/src/patterns/components/tabs/tabs.twig
packages/twig/src/patterns/components/tabs/tabs.wingsuit.yml
packages/twig/src/patterns/components/tooltip/tooltip.js
packages/twig/src/patterns/components/tooltip/tooltip.twig
packages/twig/src/patterns/components/tooltip/tooltip.wingsuit.yml

This adds the Tabs component (https://bluestate.atlassian.net/browse/IDS-24) and also partially fixes the Twig version of the Tooltip.

feat(Tabs): Twig/CSS/JS

---

packages/twig/src/patterns/components/modal/modal.behavior.js
packages/twig/src/patterns/components/modal/modal.js
packages/twig/src/patterns/components/tabs/tabs.behavior.js
packages/twig/src/patterns/components/tooltip/tooltip.behavior.js

This fixes an issue caused by naming conflicts in config files in Wingsuit

fix(Wingsuit): fix config issue

---

packages/styles/scss/components/_card.scss
packages/styles/scss/components/_cardgroup.scss
packages/styles/scss/components/index.scss
packages/themes/tokens/type/base.json
packages/twig/src/patterns/components/card/card.stories.jsx
packages/twig/src/patterns/components/card/card.twig
packages/twig/src/patterns/components/card/card.wingsuit.yml
packages/twig/src/patterns/components/card/index.js
packages/twig/src/patterns/components/cardgroup/cardgroup.stories.jsx
packages/twig/src/patterns/components/cardgroup/cardgroup.twig
packages/twig/src/patterns/components/cardgroup/cardgroup.wingsuit.yml
packages/twig/src/patterns/components/cardgroup/index.js

Include many of the variations except for featured

feat(Card): multiple card variations

---

packages/styles/scss/components/_accordion.scss
packages/styles/scss/components/_callout.scss
packages/styles/scss/components/_list.scss
packages/twig/src/patterns/components/callout/callout.behavior.js
packages/twig/src/patterns/components/callout/callout.js
packages/twig/src/patterns/components/callout/callout.twig
packages/twig/src/patterns/components/callout/index.js

add spacing to the callout button label

Bugfixes - 10/12/22

---

README.md
contributing.md

The adds guidelines for potential contributors and makes some basic updates to the main docs. Edits and feedback welcome!

Docs: Add contribution guidelines

---

.changeset/dirty-wasps-wash.md
packages/styles/scss/components/_card.scss
packages/styles/scss/components/_contextmenu.scss
packages/styles/scss/components/_hero.scss
packages/twig/src/patterns/components/card/card.wingsuit.yml

Remove default card variant and hover for data card

bugfix(Card) small card fixes

---

.changeset/wise-pigs-nail.md
packages/twig/src/patterns/components/callout/callout.wingsuit.yml
packages/twig/src/patterns/components/card/card.wingsuit.yml
packages/twig/src/patterns/components/hero/hero.wingsuit.yml
packages/twig/src/patterns/components/herocard/herocard.wingsuit.yml
packages/twig/src/patterns/components/list/list.wingsuit.yml
packages/twig/src/patterns/components/navigation/navigation.wingsuit.yml
packages/twig/src/patterns/components/tags/tag.wingsuit.yml
packages/twig/src/patterns/components/tags/tags.wingsuit.yml
packages/twig/src/patterns/components/tooltip/tooltip.wingsuit.yml

Make sure wingsuit details are accurate and clear

bugfix(Documentation): go through components for extra documentation

---

.changeset/purple-chairs-exist.md
.changeset/rude-ladybugs-unite.md
packages/styles/scss/components/_card.scss
packages/styles/scss/components/_navigation.scss
packages/twig/src/patterns/components/localnav/localnav.twig
packages/twig/src/patterns/components/navigation/navigation.twig
packages/twig/src/patterns/components/tooltip/tooltip.js

Feature cards flex-direction column but need to be row for wide version

bugfix(Card): Feature card wide version needs correct flex-direction

---

.changeset/nice-eyes-relax.md

React/feat/270 Changeset

---

.changeset/chatty-humans-smoke.md
packages/react/.storybook/preview.tsx
packages/react/src/components/Navigation/Navigation.args.ts
packages/react/src/components/Navigation/Navigation.props.ts
packages/react/src/components/Navigation/Navigation.tsx
packages/react/src/components/Navigation/index.ts
packages/react/src/components/index.ts
packages/react/src/stories/Navigation/Navigation.mdx
packages/react/src/stories/Navigation/Navigation.stories.tsx
packages/styles/scss/components/_navigation.scss

@justintemps , please review and comment. Thx

react(feat): implemented Navigation component

---

.changeset/afraid-flowers-study.md
packages/twig/src/patterns/components/localnav/localnav.twig

Hey @wc-lei , I only saw a single section here that needed removing. Can you have a look?
Fixes #294

Fix/twig: Unneeded props and markup in localnav

---

packages/react/.storybook/preview.tsx
packages/react/src/__tests__/Accordion.test.tsx
packages/react/src/components/Accordion/Accordion.args.ts
packages/react/src/stories/Accordion/Accordion.stories.tsx
packages/react/src/stories/List/List.stories.tsx
packages/react/src/stories/SearchField/SearchField.stories.tsx

This fixes code not appearing in the React Storybook canvas

Docs(react): Fix code not appearing in SB canvas

---

.changeset/chilly-monkeys-yell.md
.changeset/four-comics-cheer.md
packages/react/src/components/Card/Card.args.ts
packages/react/src/components/Card/Card.props.ts
packages/react/src/components/Card/Card.tsx
packages/react/src/components/Card/CardGroup.args.ts
packages/react/src/components/Card/CardGroup.props.ts
packages/react/src/components/Card/CardGroup.tsx
packages/react/src/components/Card/index.ts
packages/react/src/components/index.ts
packages/react/src/stories/Card/Card.mdx
packages/react/src/stories/Card/Card.stories.tsx
packages/react/src/stories/CardGroup/CardGroup.mdx
packages/react/src/stories/CardGroup/CardGroup.stories.tsx
packages/react/src/types/index.ts
packages/styles/scss/components/_card.scss
packages/styles/scss/components/_profile.scss
packages/twig/importprefix.js
packages/twig/package.json
packages/twig/src/patterns/components/card/card.twig
packages/twig/src/patterns/components/profile/profile.twig
packages/twig/src/patterns/components/profile/profile.wingsuit.yml

This commit also covers a patch fix issue #299.

feat(react): Implementation of Card and CardGroup components

---

.changeset/twelve-coats-smile.md
packages/styles/README.md
packages/styles/scss/global.scss

Fix/Styles: export global css styles to be used alongside component css

---

.changeset/chilly-ladybugs-deliver.md
packages/twig/src/patterns/components/card/card.twig

Added blocks to wrap images on the card component to use Drupal responsive images.

feat(twig): add blocks to wrap card component images

---

.changeset/fifty-camels-appear.md
packages/twig/src/patterns/components/breadcrumb/breadcrumb.behavior.js
packages/twig/src/patterns/components/callout/callout.behavior.js
packages/twig/src/patterns/components/loading/loading.behavior.js
packages/twig/src/patterns/components/modal/modal.behavior.js
packages/twig/src/patterns/components/navigation/navigation.behavior.js
packages/twig/src/patterns/components/notification/notification.behavior.js
packages/twig/src/patterns/components/readmore/readmore.behavior.js
packages/twig/src/patterns/components/table/table.behavior.js
packages/twig/src/patterns/components/tableofcontents/tableofcontents.behavior.js
packages/twig/src/patterns/components/tabs/tabs.behavior.js
packages/twig/src/patterns/components/tags/tag.behavior.js
packages/twig/src/patterns/components/tooltip/tooltip.behavior.js
packages/twig/src/patterns/components/video/video.behavior.js

* feat(twig): Add if statement to all Drupal.behaviors to only run the function once

Bump Twig version

---

.changeset/clever-rice-exist.md
.changeset/real-spoons-allow.md
.changeset/weak-forks-thank.md
packages/styles/scss/components/_navigation.scss
packages/twig/src/patterns/components/navigation/navigation.behavior.js
packages/twig/src/patterns/components/navigation/navigation.js
packages/twig/src/patterns/components/navigation/navigation.wingsuit.yml
packages/twig/src/patterns/components/notification/notification.behavior.js

This fixes #385. Could you have a look at this @PauZoocha and see if it fixes the issue?

Fix/twig: menu visibility and bubbling issues

---

.changeset/lemon-berries-hug.md
packages/styles/scss/components/_hero.scss

Fix/styles: correct hero card max width

---

.changeset/dry-jars-melt.md
.changeset/spicy-scissors-share.md
packages/styles/scss/components/_video.scss
packages/twig/src/patterns/components/video/video.js
packages/twig/src/patterns/components/video/videoplayer.twig

- Change request for videojs player to be able to work with Youtube videos

feat(twig-styles): videojs and youtube.

---

.changeset/wise-kids-act.md
packages/twig/src/patterns/components/card/card.twig
packages/twig/src/patterns/components/card/card.wingsuit.yml
packages/twig/src/patterns/components/image/image.twig
packages/twig/src/patterns/components/image/image.wingsuit.yml

- Needed to change this attribute to be able to apply the breakpoint value that comes from Drupal - eg. `media= "all and (min-width: 480px)"`

feat(twig): Change media attribute for responsive images

---

.changeset/smooth-yaks-peel.md
packages/twig/src/patterns/components/card/card.twig
packages/twig/src/patterns/components/cardgroup/cardgroup.twig
packages/twig/src/patterns/components/cardgroup/cardgroup.wingsuit.yml

- Add **Alt** and **Loading** card variables into the card include on cardgroup template.

feat(twig): Add new Alt and Loading card variables into cardgroup template.

---

.changeset/great-falcons-attend.md
.changeset/healthy-pots-watch.md
.changeset/metal-olives-happen.md
.changeset/smart-shrimps-grow.md
packages/styles/scss/components/_hero.scss
packages/styles/scss/components/_herocard.scss
packages/styles/scss/components/_tooltip.scss
packages/styles/scss/components/index.scss
packages/themes/tokens/color/tooltip.json
packages/twig/src/patterns/components/hero/hero.twig
packages/twig/src/patterns/components/hero/hero.wingsuit.yml
packages/twig/src/patterns/components/herocard/herocard.twig
packages/twig/src/patterns/components/herocard/herocard.wingsuit.yml
packages/twig/src/patterns/components/tooltip/tooltip.twig
pnpm-lock.yaml

This is total refactor of the Hero and Hero Card components. It exposes the layout and styling options more explicitly and removes opaque arguments that refer to specific templates, which could change and don't say anything about what effect they're supposed to have on the component.
As such, it introduces a minor release with a breaking change, which is only permitted because the Design System is still in <v.1.0.0
In order to create a Hero for a given template, rather than passing the name of that template to the hero, you will combine the different layout and styling options available in the Hero and Hero Card component to achieve the desired layout. The different arguments have been documented in the Storybook project and you can toggle the different arguments in the settings table to …

Feat/Twig: hero and hero card refactor

---

.changeset/kind-feet-fly.md
.changeset/tiny-impalas-learn.md
packages/react/src/components/Navigation/Navigation.args.ts
packages/styles/scss/components/_navigation.scss
packages/twig/src/patterns/components/navigation/navigation.js

fix(react): #426 label and icon are not aligned

---

.changeset/brave-bikes-refuse.md
packages/themes/tokens/fonts/base.json

Feat(themes): specify system fonts for Chinese and Japanese

---

.changeset/big-fireants-agree.md
.changeset/cuddly-parents-think.md
.changeset/gold-eagles-sparkle.md
.changeset/itchy-dryers-compete.md
.changeset/silver-birds-float.md
.changeset/sweet-suits-remember.md
packages/styles/scss/components/_container.scss
packages/styles/scss/components/_footer.scss
packages/styles/scss/components/_navigation.scss
packages/styles/scss/components/_socialmedia.scss
packages/styles/scss/components/index.scss
packages/themes/tokens/layout/base.json
packages/twig/src/patterns/components/footer/footer.twig
packages/twig/src/patterns/components/footer/footer.wingsuit.yml
packages/twig/src/patterns/components/navigation/navigation.twig

The main goal of this PR is to fit the Footer content into a max-width container so that it will align with the rest of the content on the page.
In the process, it also does the following:
- Adds tokens for content `maxWidth` and `padding` 
- Adds a layout `.container` class with theme values
- Uses the class to replace the values hard coded in the `Navigation` component
- Uses the class to wrap content in the Footer
Along the way, we fixed several styling issues in the Footer including RTL styles
Fixes #333 
Fixes #432 
Fixes #443 
Fixes #433 
This includes changes to the markup in both the `Navigation` and `Footer` components that will also need to be updated in the `@ilo-org/react` package.

Twig/Styles: Various footer updates

---

.changeset/strange-baboons-train.md
.changeset/sweet-papayas-dream.md
packages/styles/scss/components/_herocard.scss
packages/styles/scss/components/_tooltip.scss
packages/themes/tokens/spacing/base.json
packages/twig/src/patterns/components/hero/hero.twig
packages/twig/src/patterns/components/hero/hero.wingsuit.yml
packages/twig/src/patterns/components/tooltip/tooltip.twig
packages/twig/src/patterns/components/tooltip/tooltip.wingsuit.yml

Fix(Twig/Styles): Correct hero Card width and fix caption icon

---

.changeset/strong-gifts-act.md
packages/styles/scss/components/_pagination.scss
packages/twig/src/patterns/components/pagination/pagination.twig

Remove current page operators and add margin bottom to the element.

feat(twig-styles): Pagination

---

.changeset/strong-gifts-act.md
packages/styles/scss/components/_pagination.scss
packages/twig/src/patterns/components/pagination/pagination.twig

Reverts international-labour-organization/designsystem#557

Revert "feat(twig-styles): Pagination"

---

.changeset/chilled-pans-listen.md
.changeset/dull-pianos-itch.md
.changeset/slow-snails-rule.md
packages/styles/scss/components/_datacard.scss
packages/twig/src/patterns/components/card_data/card_data.twig
packages/twig/src/patterns/components/card_data/card_data.wingsuit.yml

Twig/Styles: Data Card CTA and Spacing Issues

---

.changeset/shy-sheep-hammer.md
packages/styles/scss/components/_accordion.scss
packages/twig/src/patterns/components/accordion/accordion-item.twig
packages/twig/src/patterns/components/accordion/accordion.js
packages/twig/src/patterns/components/accordion/accordion.twig
packages/twig/src/patterns/components/modal/modal.twig

Fix(twig/styles): make accordion work properly in modal

---

.changeset/quiet-horses-agree.md
packages/styles/scss/components/_callout.scss
packages/twig/src/patterns/components/callout/callout.twig
packages/twig/src/patterns/components/callout/callout.wingsuit.yml

Fixes #549
@inesdgomes please check the deploy preview here: https://deploy-preview-616--ilo-ui-twig.netlify.app/?path=/docs/components-feedback-callout--callout

Fix(styles): Callout 

---

.changeset/cuddly-carrots-care.md
packages/styles/scss/components/_profile.scss
packages/twig/src/patterns/components/profile/profile.twig
packages/twig/src/patterns/components/profile/profile.wingsuit.yml

Fixes #550 
Fixes #551 
Fixes #567 
Fixes #350

Fix(styles/twig): profile component

---

.changeset/mighty-garlics-shake.md
packages/styles/scss/components/_tabs.scss

Fix(styles): scrollbar appearing in tab content

---

.changeset/wicked-paws-protect.md
packages/styles/scss/components/_card.scss
packages/styles/scss/components/_statcard.scss
packages/twig/src/patterns/components/card_stat/card_stat.twig

Fix(twig/styles): align source to bottom of stat card

---

.changeset/proud-gorillas-confess.md
packages/styles/scss/components/_navigation.scss

fix(styles): make logo appear in nav in Firefox

---

.changeset/sharp-peas-brush.md
packages/react/src/components/Hero/HeroCard.tsx
packages/twig/src/patterns/components/herocard/herocard.twig

Change : - 
* Change the position of the date to be below the description as required in the design
Issue link :- https://github.com/international-labour-organization/designsystem/issues/568

Style(react): Hero card date position

---

.changeset/hot-islands-cry.md
packages/styles/scss/components/_hero.scss

Fix/Styles: Hero caption in rtl

---

.changeset/lucky-doors-laugh.md
.changeset/seven-toes-behave.md
.changeset/thin-poems-dance.md
.changeset/twelve-badgers-pump.md
packages/styles/scss/_mixins.scss
packages/styles/scss/components/_card.scss
packages/styles/scss/components/_detailcard.scss
packages/styles/scss/components/_textcard.scss

- Adjust Detail and Text Card Spacing
- Give both cards a blue bottom border on hover

Fix/styles Detail & Text card spacing and borders

---

.changeset/beige-hounds-ring.md
packages/react/src/components/Hero/Hero.args.ts
packages/react/src/components/Hero/Hero.props.ts
packages/react/src/components/Hero/Hero.tsx

Fixes https://github.com/international-labour-organization/designsystem/issues/562
* Added background on offset
* Added offset to breadcrumbs
* Set default value to breadcrumbs for react storybook
Before
After

fix(react)- Sync hero with twig implementation

---

.changeset/hot-cherries-grow.md
packages/styles/scss/components/_card.scss

Fixes :- https://github.com/international-labour-organization/designsystem/issues/573
* Made transition-timing smoother
* Fixed light theme hover issue

fix(styles)- Make card animations smoother

---

.changeset/famous-points-approve.md
packages/styles/scss/components/_accordion.scss

Fixes :- https://github.com/international-labour-organization/designsystem/issues/572
Notes :- 
* Added spacing to the bottom of the panel when its open. 
* Considering the above padding of 20px that is added only 36px needs to be added to satisfy the design.

Fix(style) - Accordion spacing

---

.changeset/fair-rabbits-shop.md
packages/styles/scss/components/_tooltip.scss
packages/twig/package.json
packages/twig/src/patterns/components/tooltip/tooltip.js
packages/twig/src/patterns/components/tooltip/tooltip.twig
pnpm-lock.yaml

Fixes [#532](https://github.com/international-labour-organization/designsystem/issues/532)
Fixes #711 
**_Changes are only done in twig_**
* Implemented [Popper.js](https://popper.js.org/) to handle the tooltip.
* Modified styling and js as required to support popper.js
* Priority of tooltip will be Top,Bottom,Right,Left as @inesdgomes suggested.
* Considered mobile devices when screen size is below medium (Same screen size measuring in other components), the max width remains at 180px.
Cc :- @justintemps
Long tooltip (More than 50 chars)
Normal tooltip (Less than 50 chars)

fix(styles): Used popper library to handle tooltip

---

.changeset/fuzzy-emus-approve.md
packages/styles/scss/components/_accordion.scss

Fixes :- https://github.com/international-labour-organization/designsystem/issues/722
* Add right margin to accordion to prevent overflow

Fix(style)- Add margin styling to accordion

---

.changeset/ten-stingrays-march.md
packages/styles/scss/components/_card.scss
packages/twig/src/patterns/components/card_multilink/card_multilink.twig
packages/twig/src/patterns/components/card_multilink/card_multilink.wingsuit.yml

Fixes :- https://github.com/international-labour-organization/designsystem/issues/718
**_Changes are only done in twig_**
* Added eyebrow to multilinkcard. 
* Make the spacing between the eyebrow and the heading consistent with the design.
* Eyebrow (Standard) 
* Eyebrow (Standard/ Hover)
* Eyebrow (Wide)

fix(twig) - Add eyebrow to multilink card

---

.changeset/sour-bats-shake.md
packages/twig/src/patterns/components/tabs/tabs.twig

Fixes https://github.com/international-labour-organization/designsystem/issues/767
* Refactor role=tab position in the direct child element of the tablist.

fix(twig) - Refactor role position in tabs

---

.changeset/slow-baboons-occur.md
packages/styles/scss/components/_hero.scss

Fixes https://github.com/international-labour-organization/designsystem/issues/782
* Currently the breadcrumb is only displayed to larger devices in the hero component. 
* Remove the property which sets the breadcrumb to only be included in large devices

fix(style) : Breadcrumb hidden in small devices

---

.changeset/late-worms-live.md
packages/styles/scss/components/_cardgroup.scss
packages/styles/scss/components/_profile.scss

Fixes https://github.com/international-labour-organization/designsystem/issues/469
Verified all of the cards

fix(style) : Spacing issues in cards

---

.changeset/mighty-moose-trade.md
packages/styles/scss/components/_icon.scss
packages/styles/scss/components/index.scss
packages/twig/src/patterns/components/icon/icon.behavior.js
packages/twig/src/patterns/components/icon/icon.js
packages/twig/src/patterns/components/icon/icon.stories.jsx
packages/twig/src/patterns/components/icon/icon.twig
packages/twig/src/patterns/components/icon/icon.wingsuit.yml
packages/twig/src/patterns/components/icon/index.js

Introducing a new icon component for twig 
https://github.com/international-labour-organization/designsystem/assets/36326203/293ae5eb-2005-4615-a234-e755f880274d
The icon component accepts 3 props
- **name** - name of the icon, any icon from `@ilo-org/icons` package, case sensitive. [Full list](https://github.com/international-labour-organization/designsystem/tree/develop/packages/icons/src/svg)
- **size**  - the fixed size of an icon, can be: `16`, `20`, `24`, or `32`. Optional
- **color** - any arbitrary CSS color value: `color`, `hex`, `rgb`, `rgba`, `hsl`. Optional
so twig template will look like this 
```twig
{% include "@components/icon/icon.twig" with {
"name": "Facebook",
"size": "32",
"color": "hsl(50 80% 40%)"
} %}
```
As discussed in #692, the Icon component is done via the …

Twig Icon Component

---

.changeset/unlucky-pots-taste.md
packages/react/src/components/Input/Input.props.ts
packages/react/src/components/Input/Input.tsx
packages/react/src/components/SearchField/SearchField.args.ts
packages/react/src/components/SearchField/SearchField.tsx

Fixes https://github.com/international-labour-organization/designsystem/issues/708
* Currently there is no clear button in the search textfield
* Add X icon to search field when text is entered

feat(react) - Add clear button to search

---

packages/twig/src/patterns/components/button/button.twig
packages/twig/src/patterns/components/button/button.wingsuit.yml

Fixes a bug that prevented icons from rendering in the button

Fix(twig): fix icon rendering, update docs

---

.changeset/healthy-crews-press.md
packages/react/.npmignore

Right now the React package bundle looks something like that 
---
React  package includes storybook args within a component directory, for example, the accordion component
the arg files are only used for the storybook and we should store them with story files
> Before
> After

React bundle reduce 

---

packages/react/src/components/Cards/CardGroup/CardGroup.args.ts

Fixes https://github.com/international-labour-organization/designsystem/issues/869
* Cardgroup docs in react are not having a proper structure and layout
* Add atleast 4 components to each relevant cardgroup
* Sync profile component theme classname with twig

fix(react) - refactor cardgroup docs in a proper layout

---

package.json
packages/brand-assets/package.json
packages/fonts/package.json
packages/icon-build-helpers/package.json
packages/icons-react/package.json
packages/icons/package.json
packages/react/package.json
packages/styles/package.json
packages/themes/package.json
packages/twig/package.json
packages/utils/package.json

Fix(core): update contributors

---

.changeset/unlucky-eyes-own.md
packages/twig/src/patterns/components/accordion/accordion-item.twig
packages/twig/src/patterns/components/accordion/accordion.wingsuit.yml
packages/twig/src/patterns/components/button/button.wingsuit.yml
packages/twig/src/patterns/components/callout/callout.wingsuit.yml
packages/twig/src/patterns/components/card/card.wingsuit.yml
packages/twig/src/patterns/components/card_detail/card_detail.wingsuit.yml
packages/twig/src/patterns/components/card_feature/card_feature.wingsuit.yml
packages/twig/src/patterns/components/card_multilink/card_multilink.wingsuit.yml
packages/twig/src/patterns/components/card_promo/card_promo.wingsuit.yml
packages/twig/src/patterns/components/cardgroup/cardgroup.wingsuit.yml
packages/twig/src/patterns/components/datepicker/datepicker.wingsuit.yml
packages/twig/src/patterns/components/fileupload/fileupload.wingsuit.yml
packages/twig/src/patterns/components/herocard/herocard.wingsuit.yml
packages/twig/src/patterns/components/icon/icon.wingsuit.yml
packages/twig/src/patterns/components/image/image.wingsuit.yml
packages/twig/src/patterns/components/list/list-item.twig
packages/twig/src/patterns/components/pagination/pagination.wingsuit.yml
packages/twig/src/patterns/components/readmore/readmore.twig
packages/twig/src/patterns/components/readmore/readmore.wingsuit.yml
packages/twig/src/patterns/components/richtext/richtext.twig
packages/twig/src/patterns/components/table/table.twig
packages/twig/src/patterns/components/table/table.wingsuit.yml
packages/twig/src/patterns/components/tags/tag.wingsuit.yml
packages/twig/src/patterns/components/tags/tags.wingsuit.yml
packages/twig/src/patterns/components/textarea/textarea.wingsuit.yml
packages/twig/src/patterns/components/tooltip/tooltip.twig
packages/twig/src/patterns/components/tooltip/tooltip.wingsuit.yml

#895 Fix wingsuit YAML definitions

---

.changeset/pink-wasps-rush.md
config/eslint-config/package.json
config/prettier-config/package.json
config/typescript-config/package.json
package.json
packages/brand-assets/package.json
packages/fonts/package.json
packages/icon-build-helpers/package.json
packages/icons-react/package.json
packages/icons/package.json
packages/react/package.json
packages/styles/package.json
packages/themes/package.json
packages/twig/package.json
packages/utils/package.json

Re-set files field in package.json of the package rather than at the monorepo root

Reset files in local package.json

---

.changeset/loud-needles-cover.md
packages/react/src/components/Cards/CardGroup/CardGroup.args.ts
packages/react/src/components/Cards/CardGroup/CardGroup.props.ts
packages/react/src/components/Cards/CardGroup/CardGroup.tsx
packages/react/src/components/Cards/FactlistCard/FactListCard.tsx
packages/react/src/components/Cards/MultilinkCard/MultiLinkCard.tsx
packages/react/src/stories/CardGroup/CardGroup.stories.tsx

Fixes https://github.com/international-labour-organization/designsystem/issues/922
* Some of the storybook controls for cardgroup is not available in react.

fix(react) -Sync cardgroup controls with twig

---

.changeset/silent-avocados-end.md
config/eslint-config/LICENSE
config/eslint-config/README.md
config/prettier-config/LICENSE
config/prettier-config/README.md
config/typescript-config/LICENSE
config/typescript-config/README.md

The bumps the following packages to version 1:
- `@ilo-org/eslint-config`
- `@ilo-org/prettier-config`
- `@ilo-org/typescript-config`

Version 1 Release for Config Packages

---

.changeset/fluffy-wombats-reply.md
.changeset/rich-boats-run.md
packages/styles/scss/components/_breadcrumb.scss
packages/twig/src/patterns/components/breadcrumb/breadcrumb.js
packages/twig/src/patterns/components/breadcrumb/breadcrumb.twig

- Prevent Breadcrumb from overflowing its container
- Minor a11y fixes

Twig: Breadcrumb Fixes

---

.changeset/purple-apes-sort.md
packages/styles/scss/_functions.scss
packages/styles/scss/_mixins.scss

Fixes https://github.com/international-labour-organization/designsystem/issues/966
* Currently there are a few unused functions/mixins which needs to be cleaned up.
**Animations**
* N/A
**Functions**
* Encode color
**Mixins**
* Vertical align
* Horizontal align
* Vertical horizontal align
* Ellipsis
* Spacing values
* Icon button

fix(styles) - cleanup unused functions/mixins

---

.changeset/dull-coats-turn.md
packages/react/src/components/Breadcrumb/Breadcrumb.args.ts
packages/react/src/components/Breadcrumb/Breadcrumb.props.ts
packages/react/src/components/Breadcrumb/Breadcrumb.tsx
packages/react/src/components/ContextMenu/ContextMenu.tsx
packages/react/src/stories/Breadcrumb/Breadcrumb.mdx

This provides a complete refactor of the Breadcrumb and fixes several accessibility issues in the process.

React: Align Breadcrumb with Twig

---

.changeset/silent-poems-greet.md
packages/styles/scss/components/_richtext.scss

Fix(styles): RichText link decoration

---

packages/twig/.eslintrc.js
packages/twig/cypress/e2e/cards/data-card.cy.js
packages/twig/cypress/e2e/cards/detail-card.cy.js
packages/twig/cypress/e2e/cards/fact-list-card.cy.js
packages/twig/cypress/e2e/cards/feature-card.cy.js
packages/twig/cypress/e2e/cards/multi-link-card.cy.js
packages/twig/cypress/e2e/cards/promo-card.cy.js
packages/twig/cypress/e2e/cards/stat-card.cy.js
packages/twig/cypress/e2e/cards/text-card.cy.js
packages/twig/cypress/support/commands.js

Initial implementation of cards of :- 
* Create tests for card rendering
* Refactored getPreview function to match individual components.
* Ad cy to eslint to fixglobal usage error.
* As discussed we will be initially checking if the cards render as expected. 
* Variants will be handled later.

test(twig) :  Initial tests for card rendering

---

packages/twig/cypress/e2e/feedback/callout.cy.js
packages/twig/cypress/e2e/feedback/modal.cy.js
packages/twig/cypress/e2e/feedback/notification.cy.js
packages/twig/cypress/e2e/feedback/tooltip.cy.js

Initial implementation of feedback :- 
* Create tests for feedback rendering

test(twig) : Initial tests for feedback

---

packages/twig/cypress/e2e/content/accordion.cy.js
packages/twig/cypress/e2e/content/hero-card.cy.js
packages/twig/cypress/e2e/content/list.cy.js
packages/twig/cypress/e2e/content/profile.cy.js
packages/twig/cypress/e2e/content/richtext.cy.js
packages/twig/cypress/e2e/content/table.cy.js

Initial implementation of content :- 
* Create tests for content rendering

test(twig) : Initial tests for content

---

packages/twig/cypress.config.js
packages/twig/cypress/e2e/navigation/breadcrumb.cy.js
packages/twig/cypress/e2e/navigation/context-menu.cy.js
packages/twig/cypress/e2e/navigation/footer.cy.js
packages/twig/cypress/e2e/navigation/link-list.cy.js
packages/twig/cypress/e2e/navigation/link.cy.js
packages/twig/cypress/e2e/navigation/local-nav.cy.js
packages/twig/cypress/e2e/navigation/navigation.cy.js
packages/twig/cypress/e2e/navigation/pagination.cy.js
packages/twig/cypress/e2e/navigation/social-media.cy.js
packages/twig/cypress/e2e/navigation/table-of-contents.cy.js

Initial implementation of navigation :- 
* Create tests for navigation rendering

test(twig): Initial tests for navigation

---

packages/twig/cypress/e2e/media/image.cy.js
packages/twig/cypress/e2e/media/logo-grid.cy.js
packages/twig/cypress/e2e/media/video.cy.js

Initial implementation of tests for media :- 
* Create tests for media

test(twig): add initial tests for media

---

.changeset/dry-lamps-juggle.md
packages/react/src/components/Input/Input.tsx
packages/react/src/components/Navigation/Navigation.tsx
packages/react/src/components/SearchField/SearchField.tsx
packages/twig/src/components/navigation/navigation.js

Fixes https://github.com/international-labour-organization/designsystem/issues/1050
**Note :-** 
* When we click the search button in the navigation component. The user has to manually click the search input field which is hindering the UX.
**Fix :-**
* Automatically focus the search input field on button click
**Demo :-** 
https://github.com/user-attachments/assets/c8ef5cb5-65ea-49ff-8a50-86f23f97b6ce

feat(react-twig): focus search input field on button click

---

.changeset/late-ducks-occur.md
packages/fonts/README.md

This contains no changes, but releases these packages as a stable version 1

Version 1 Release for brand-assets, fonts and icons

---

.changeset/cold-bobcats-think.md
packages/icons/README.md
packages/icons/categories.yml
packages/icons/icons.yml
packages/icons/src/svg/download.svg

Fixes : https://github.com/international-labour-organization/designsystem/issues/1042
* Added download icon to icon package.

feat(icon) : add download icon to package

---

.changeset/silly-donkeys-play.md
.github/workflows/test.yml
packages/twig/cypress/e2e/navigation/navigation.cy.js
packages/twig/src/components/navigation/navigation.js

Fixes https://github.com/international-labour-organization/designsystem/issues/1176
* Query search input by tag instead of class
* Modify unit test to check if input is focused after search button click
* Update base theme version to use 0.4.0

fix(twig) : refactor search input to be selected by tag

---

packages/styles/scss/_normalize.scss
packages/styles/scss/_reset.scss

This PR adds a short doc about CSS reset strategy.

CSS Reset docs

---

packages/react/src/stories/docs/styles/welcome.scss
packages/react/src/stories/docs/welcome.mdx
packages/twig/stories/docs/styles/welcome.scss
packages/twig/stories/docs/welcome.mdx

Fixes https://github.com/international-labour-organization/designsystem/issues/1188
* Fix triangle going above text on welcome screen
* Fix get started link not showing 
* Sync styles with react and twig.

fix(docs): design bugs on welcome page

---

packages/react/src/stories/docs/welcome.mdx
packages/twig/stories/docs/welcome.mdx

* Fixes the get started button

docs(react-twig) - fix get started button

---

.changeset/poor-colts-allow.md
packages/react/src/components/Cards/CardGroup/CardGroup.props.ts
packages/react/src/components/Cards/CardGroup/CardGroup.tsx
packages/react/src/components/Collapse/Collapse.tsx
packages/react/src/components/Icon/Icon.tsx
packages/react/src/components/Image/Image.props.ts
packages/react/src/components/Image/Image.tsx
packages/react/src/components/Input/Input.tsx
packages/react/src/components/Logo/Logo.tsx
packages/react/src/components/TableOfContents/TableOfContents.tsx
packages/react/src/components/Tag/TagSet.tsx
packages/react/src/utils/createChainedFunction.ts
packages/twig/cypress/e2e/navigation/local-nav.cy.js
packages/twig/cypress/e2e/navigation/navigation.cy.js

This PR fixes all `//ESLINT-DEBT`  comments, without introducing any regressions or side effects 
| File | Scope |
|--------|--------|
| `local-nav.cy.js` | twig, test |
| `navigation.cy.js`  | twig test |
| `createChainedFunction.ts` | react, util |
| `TagSet.tsx` | react, component |
| `TableOfContents.tsx` | react, component | 
| `Logo.tsx` | react, component | 
| `Icon.tsx` | react, component | 
| `Image.tsx` | react, component | 
| `TableOfContents.tsx` | react, component | 
| `Collapse.tsx` | react, component | 
| `CardGroup.tsx` | react, component |

ESLint debt

---

.changeset/new-tools-tap.md
packages/styles/scss/components/_richtext.scss

This PR adjusts the color and size of `<hr/>` inside the Richtext component

Richtext Horizontal Rule 

---

.changeset/shaggy-walls-shake.md
packages/styles/scss/components/_promocard.scss

This PR fixes the text size of the narrow promo card based on the design

Narrow Promo Card

---

.changeset/rude-clocks-learn.md
packages/styles/scss/_mixins.scss

This PR updates the bottom decoration color for the link based on the design

Link Bottom Border

---

.changeset/four-fishes-cross.md
packages/styles/scss/components/_breadcrumb.scss

Fix(styles): rtl breadcrumb.

---

packages/twig/docker-compose.yml

This PR fixes the `index.css` mapping inside the docker volume
Uploading Screen Recording 2025-01-28 at 18.28.29.mov…

CSS Mapping inside docker  volume

---

.changeset/rotten-pandas-love.md
packages/styles/scss/_mixins.scss
packages/styles/scss/components/_list.scss
packages/twig/cypress/e2e/content/list.cy.js
packages/twig/cypress/fixtures/list.json

Fix/Styles: list spacing and alignment. 

---

.changeset/many-moose-kneel.md
packages/styles/scss/components/_featurecard.scss
packages/styles/scss/theme/_foundation.scss
packages/twig/cypress/e2e/cards/feature-card.cy.js
packages/twig/cypress/fixtures/featurecard.json
packages/twig/src/components/card_feature/card_feature.component.yml
packages/twig/src/components/card_feature/card_feature.twig

Fix(Twig/Styles): Feature card bugs in dark theme

---

.changeset/late-birds-fetch.md
.changeset/nice-turkeys-tie.md
packages/react/src/components/Blockquote/Blockquote.props.ts
packages/react/src/components/Blockquote/Blockquote.tsx
packages/react/src/components/Blockquote/index.ts
packages/react/src/stories/Blockquote/Blockquote.stories.tsx
packages/react/tests/Blockquote.test.tsx
packages/styles/scss/components/_blockquote.scss
packages/styles/scss/components/_richtext.scss
packages/styles/scss/components/index.scss
packages/twig/cypress/e2e/content/blockquote.cy.js
packages/twig/cypress/fixtures/blockquote.json
packages/twig/src/components/blockquote/blockquote.component.yml
packages/twig/src/components/blockquote/blockquote.twig
packages/twig/stories/blockquote.stories.js

Implements the Blockquote comonent in React.
Only merge this after #1319

React: add standalone blockquote component

---

packages/react/src/components/Cards/MultiLinkCard.tsx
packages/react/tests/MultiLinkCard.test.tsx

Feat: Add theme to Multilink

---

.changeset/sour-walls-smell.md
packages/styles/scss/components/_video.scss

Fix/Styles: in video, fix volume button not appearing

---

.changeset/purple-trees-appear.md
packages/react/src/components/Cards/DataCard.tsx
packages/react/tests/DataCard.test.tsx

fix(react): data card only has two cols if size is wide or fluid

---

.changeset/few-fans-fly.md
packages/twig/cypress/e2e/navigation/languagetoggle.cy.js
packages/twig/cypress/fixtures/languagetoggle.json
packages/twig/src/components/languagetoggle/languagetoggle.behavior.js
packages/twig/src/components/languagetoggle/languagetoggle.component.yml
packages/twig/src/components/languagetoggle/languagetoggle.js
packages/twig/src/components/languagetoggle/languagetoggle.twig
packages/twig/stories/languagetoggle.stories.js

This implements #1337 for Twig following the same spec and with a full suite of tests.
⚠️ Merge this after #1347 
🛠️ Fixes #1345

Feat(Twig): Language Toggle

---

.changeset/beige-roses-retire.md
.changeset/chilled-moles-begin.md
.changeset/poor-kids-argue.md
.changeset/spicy-peaches-change.md
packages/react/src/components/Button/Button.tsx
packages/react/src/components/Cards/ScoreCard.tsx
packages/react/src/components/Cards/index.ts
packages/react/src/components/Picture/Picture.tsx
packages/react/src/components/Picture/index.ts
packages/react/src/components/Status/Status.tsx
packages/react/src/components/Status/index.ts
packages/react/src/stories/Card/ScoreCard.stories.tsx
packages/react/src/stories/Icon/Icon.stories.tsx

This adds the ScoreCard to React.
Fixes #1314  
Fixes #1350
This should be merged after #1358 and #1365

React: ScoreCard

---

.changeset/strong-swans-move.md
packages/twig/cypress/e2e/content/accordion.cy.js
packages/twig/cypress/fixtures/accordion.json
packages/twig/src/components/accordion/accordion-item.twig

Fix(twig): accordion item configurable ids

---

.changeset/chatty-mugs-reflect.md
.changeset/chilly-papayas-sniff.md
.changeset/five-countries-sparkle.md
.changeset/good-mirrors-visit.md
.changeset/lazy-rocks-act.md
.changeset/metal-sloths-know.md
.changeset/popular-berries-change.md
packages/styles/scss/components/_card.scss
packages/styles/scss/components/_cardgroup.scss
packages/styles/scss/components/_detailcard.scss
packages/styles/scss/components/_profile.scss
packages/styles/scss/components/_promocard.scss
packages/styles/scss/components/_tag.scss
packages/twig/cypress/e2e/cards/promo-card.cy.js
packages/twig/cypress/fixtures/promocard.json
packages/twig/src/components/card_promo/card_promo.component.yml
packages/twig/src/components/card_promo/card_promo.twig

Various style fixes

---

.changeset/honest-planets-know.md
packages/react/src/components/Cards/DetailCard.tsx
packages/react/src/components/Cards/ScoreCard.tsx

This PR introduces the changes done in the canary branch for the @ilo-org/react package.
- **DetailCard:** Add an option to swap the link component
- **ScoreCard:** Add an option to swap the link component

Canary Batch

---

.changeset/friendly-terms-relate.md
packages/twig/cypress/e2e/content/accordion.cy.js
packages/twig/src/components/accordion/accordion-item.twig

Fix(twig): make sure accordion aria-expanded always set

---

.changeset/gentle-trees-fold.md
packages/styles/scss/components/_languagetoggle.scss
packages/styles/scss/components/navigation/_nav-complex.scss
packages/styles/scss/components/navigation/_nav-menu.scss

Styles: Update subsite nav styles

---

.changeset/lucky-bobcats-shake.md
packages/styles/scss/components/_scorecard.scss

Styles: Dark Theme Score Card issues

---

.changeset/blue-cameras-cover.md
.changeset/funny-tips-grow.md
.changeset/pretty-dolls-pay.md
packages/react/src/components/Fieldset/Fieldset.props.ts
packages/react/src/components/Fieldset/Fieldset.tsx
packages/react/src/components/Form/Form.props.ts
packages/react/src/components/Form/Form.tsx
packages/react/src/components/FormControl/FormControl.props.ts
packages/react/src/components/FormControl/FormControl.tsx
packages/react/src/components/Tooltip/Tooltip.tsx
packages/react/src/stories/Dropdown/Dropdown.stories.tsx
packages/react/src/stories/Form/Form.stories.tsx
packages/react/src/types/forms.args.ts
packages/styles/scss/components/_fieldset.scss
packages/styles/scss/components/_form.scss
packages/styles/scss/components/_formcontrol.scss
packages/twig/src/components/form/fieldset.twig
packages/twig/src/components/form/form.component.yml
packages/twig/src/components/form/form.twig
packages/twig/src/components/form/formcontrol.twig

Form elements supports dark theme

---

.changeset/violet-boxes-smile.md
packages/react/src/stories/Card/MultiLinkCard.stories.tsx
packages/react/src/stories/Status/Status.stories.tsx
packages/styles/scss/components/_datacard.scss
packages/styles/scss/components/_multilinkcard.scss

Fixes #1464 
Fixes #1474 
Fixes #1473

Various patches

---

.changeset/spicy-guests-wash.md
packages/react/src/components/index.ts

Correctly export Status component from React

fix(react): export Status

---

packages/styles/scss/components/_checkbox.scss

fix(styles): checkbox remove theme vars

---

.changeset/sixty-pigs-dream.md
packages/styles/scss/_typography.scss

Fixes letter spacing issue with new Arabic font

Fix(styles): new arabic font letter spacing. #1547
